### ISSUE TITLE
Image API use of `profile` does not map cleanly from RDF

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1013]
The [Image API 2.1 use of `profile`](http://iiif.io/api/image/2.1/#technical-properties) is awkward in that it requires additional rules for correct generation from RDF that cannot be described in the `@context` or  by JSON-LD framing:

> `profile` - Required - A list of profiles, indicated by either a URI or an object describing the features supported. **The first entry in the list must be a compliance level URI.**

While it seems to be a real edge-case that one might want to generate an Image API `info.json` from RDF data, it seems bad that it can't be done straightforwardly (more at [iiif-ld-demo](https://github.com/zimeon/iiif-ld-demo/blob/master/image-api/write_image_info.md)). Additionally, it is not clear that the current pattern is best for pure-JSON clients either. Possible ways to address this include:

  * separate the compliance from other profile specification (pro: would make JSON very clean, even easier for clients that just want the compliance. con: in RDF have different predicates for the same/similar notions)
  * remove ordering requirement (pro: current `@context` then OK to describe model; con: more complex for JSON client) 
  * ... ?

**Comment by workergnome** [comment]
Personal preference would be to remove the ordering requirement, since this means that a naive client could simply iterate through the provided profiles and calculate the union of them.  (This doesn't deal with conflict resolution, but neither does the existing spec.)  A more sophisticated client would know that certain URIs provided have standardized values, and not dereference them.

**Comment by azaroth42** [comment]
Related to #520.

**Comment by azaroth42** [comment]
Closing in favor of #1275.
