### ISSUE TITLE
Rename images as items

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1068]
A/V working group discussion was around adding another key for media, and decision was made that it could be easier to have one key, `"content"` (and remove `images` and `otherContent`). This will include inline and referenced AnnotationLists (relaxing the requirement that AnnotationLists be included by reference only). It should be made explicit that AnnotationLists are ordered and the most important content should be first.

**Comment by jpstroop** [comment]
And, in 3.0 it's an `AnnotationPage`, not `AnnotationList`

**Comment by jpstroop** [comment]
👍  on [25 July 2017 A/V call](https://docs.google.com/document/d/1U4zqpooslP1H0vVEvq02n1fHpCsDQPRodca571_9TFs/edit#. There may be an issue around what content should be loaded in what order. Inline first, then references? Top of the list first?

**Comment by tomcrane** [comment]
Agreed on call that "content" is the way to go, but semantics of otherContent vs inages are lost in deciding what to paint immediately and what to leave to user

**Comment by workergnome** [comment]
I think the issue, as I understand it, is that it could be useful to have a viewing hint that some content is needed for immediate view, and some could (or should) be deferred or lazy loaded, and that it might be useful to have an explicit hint.

**Comment by zimeon** [comment]
Have separated issue of rules/hints for immediate vs deferred loading (#1201) so that we can keep this issue resolved with agreement to move to `content` in presentation 3.0.

**Comment by azaroth42** [comment]
Assuming that the list is ordered, I propose `contents` rather than `content` (c.f. `items` and `structures`)

**Comment by tomcrane** [comment]
I prefer `content`, as a mass noun. We have `otherContent` in 2.

**Comment by tomcrane** [comment]
Agreement from Getty AV meeting is that the terms should be merged, but `content` is now problematic because of https://github.com/IIIF/iiif.io/issues/1262

We need a new term (working name: `stuff`)

This term is the only term used to link to annotations, throughout a manifest  (e.g., on ranges, sequences, the manifest itself). `content` feels wrong for linking a range to its annotations, the range itself does not have _content_ in the way that painting annotations on a canvas are _content_.

The term we are looking for encompasses annotations that are the _content_ of the resource (isPartOf), and annotations that are _about_ the resource, and everything else for which the relationship is hard to define (linking, bookmarking etc..). We have `motivation` on annotations to provide fine level distinctions of what an annotation is for, we don't want a fuzzy distinction at the linking property level.

A possible choice for this term is `annotations`, but the objection is that this is describing the mechanism rather than the intent. `content` was good, because it reinforced how IIIF works.

We need a name for this linking property that conveys that it gives access to all the things available to hang on the scaffolding provided by IIIF - all the intellectual content of an object, all the intellectual content about an object, all the links, and so on.

**Comment by workergnome** [comment]
`elements`?

**Comment by azaroth42** [comment]
(from #1145) Proposal: Use `items` to be consistent all the way down, and `annotations` for commentary / non-painting annotations on other resources.

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting to use `items` (as #1145)

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#items  (and throughout)
