### ISSUE TITLE
To Id Map or Not Id Map?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1072]
Given the likely introduction of nested canvases by the A/V work, should we consider [JSON-LD Id Maps](http://json-ld.org/spec/latest/json-ld/#id-maps)? The also has the potential to make it possible to collapse Sequences and Ranges into one thing.

**Comment by azaroth42** [comment]
Propose close wontfix

**Comment by jpstroop** [comment]
In the interest of developer happiness I think we should keep this open, unless there's a clear reason why it wouldn't work.

**Comment by azaroth42** [comment]
The approach wasn't popular for ranges, c.f. @glenrobson's comment about not being able to see which ranges were inside which other ranges. Happy to leave open until we can get some feedback though.

**Comment by jpstroop** [comment]
I get that, but I don't completely buy the use case that manifests need to be human readable.

**Comment by azaroth42** [comment]
@jpstroop If you still care about this issue, could you prepare a summary for Toronto?

**Comment by jpstroop** [comment]
Now that ranges are more readable, is this any more compelling?

**Comment by zimeon** [comment]
Example of use in JSON-LD docs, see `post` in https://json-ld.org/spec/latest/json-ld/#node-identifier-indexing

**Comment by azaroth42** [comment]
Getty AV Discussion, from memory:
Pro: Easy to find references to canvases, if there's more than one reference to it. E.g. from ranges,  from other canvases embedding them, or startCanvas.
Pro: Prevents clients from needing to construct the map by iteration over the Sequence
Con: Significant upheaval to the manifest structure
Con: Harder to read the document
Con: Only very small percentage of manifests would benefit (e.g. with Ranges)
Con: Makes template based construction harder

Diversion: Not all references in ranges are exactly canvas URIs, they could have fragments. Processing for this would still need to process the fragment.

**Comment by jpstroop** [comment]
Don't think I'm not watching :eyes:

**Comment by azaroth42** [comment]
Why aren't you carrying boxes around? Slacker!

**Comment by jpstroop** [comment]
🏠 is empty now!

**Comment by jpstroop** [comment]
> Pro: Easy to find references to canvases, if there's more than one reference to it. E.g. from ranges, from other canvases embedding them, or startCanvas.

Yes. Especially if Sequences go away as well.

> Pro: Prevents clients from needing to construct the map by iteration over the Sequence

Which they _all_ do.

> Con: Significant upheaval to the manifest structure

If not now when, especially since it simplifies things?

> Con: Harder to read the document

I don't think this is true--getting rid of Sequences makes it easier, and the new approach to Ranges makes the hierarchy easier to see. This would further that by making the members in `members` less verbose.

> Con: Only very small percentage of manifests would benefit (e.g. with Ranges)

Quantify? Nearly all of Princeton's manifests have Ranges, and A/V is about to introduce a lot more.

> Con: Makes template based construction harder

Impl. detail, and adding a few conditionals into the templates would solve every issue I heard at the Getty.

> Diversion: Not all references in ranges are exactly canvas URIs, they could have fragments. Processing for this would still need to process the fragment.

Yeah, this issue has no bearing on that.

**Comment by jpstroop** [comment]
Also, an external reference to a `canvasMap` could make manifests much shorter, and extending this pattern to a `serviceMap`, which could also be referenced externally, would significantly reduce redundancy for auth implementations.

**Comment by azaroth42** [comment]
The cost of the identifier map is significant for the producer and doesn't make a significant saving for the consumer -- the JSON is already parsed and the cost of iterating over a JSON array and creating a hash of `id` to the object is negligible. The code is trivial to implement.

The readability is a concern for developer happiness - if the developer has to look at the JSON of the manifest, which they very likely will, then per @glenrobson's comment about going from flat ranges to nested, the unordered hash is very difficult to work with.  That the first canvas in the representation is also the first canvas to display is a valuable feature.

I'm a strong :-1: on idMaps at the moment.

**Comment by jpstroop** [comment]
> The cost of the identifier map is significant for the producer
Why?

Also, don't understand your second paragraph? I think the map would make them _more_ readable.

**Comment by jpstroop** [comment]
Quick and dirty example: https://gist.github.com/jpstroop/7a9263286b84c451f1ad07c3cc252578

**Comment by jpstroop** [comment]
After discussion in Toronto, this _could_ be split into two issues:

 1. **Collapse Sequence into Ranges**: Range really is just a subclass of Sequence that allows for recursion. We don't have sub/super classes anywhere else in IIIF but have instead used `viewingHint` to refine how instance of different classes/structures should be handled. Getting rid of Sequence and replacing it with a Range with the "`viewingHint: : "paged"` (or something similar) would be more consistent with the rest of the spec.
 2. **ID Map or Not**: If building a canvasMap in memory is the first thing everyone does when consuming a manifest, we are doing something wrong. It's not about how trivial it is to do it, or whether or not it affects performance, it's that the convention of on making the first sequence serve double duty is awkward, and this will only become more apparent as A/V manifests begin to use Ranges for navigation, and are required to have a Sequence (or flat Range, if the previous issue was agreeable) only so that they can register their canvases for use elsewhere in the manifest.

**Comment by azaroth42** [comment]
Two pluses I could see:

* We could have zero sequences, and use hierarchical navigation only for manifests that describe something without any obvious ordering.  For example photographs taken in each room of a house could be divided up into ranges, with each range being a room, and sub ranges for different parts of the room.  There's no one true ordering across all of the photographs.
* It gives somewhere obvious to put canvases that are only ever annotated onto other canvases. I don't think this is a big deal, as the only time it's really valuable is if the same sub canvas were annotated onto multiple main canvases, and we don't (I believe) have a use case that requires this.

**Comment by tomcrane** [comment]
Or `"behavior": "sequence"`

This property says that this Range establishes the order that any next/previous/positional UI might want to use (however it might want to do that). It is not a requirement to have a Range with this property if you do not want to establish any overall order, but most manifests would have one, because most manifests of more than one canvas do represent something ordered.
 
I am warming to this. It works well for AV. And also for other manifests that are built not to model an individual work but to convey a narrative through view of multiple different works, where the canvasMap is a bucket of content and the story through it is told through careful Range construction (including segment targeting).

Would the Range with the sequence behavior be allowed to have child Ranges, so that it can do double duty as a provider of, say, the full extent of the audio of an opera including the initial audience noise right through to the curtain calls? Child and grandchild ranges allow jumping to the start of acts and start of arias, etc. without having to provide an additional top level range for the opera that has the same coverage as the special `sequence` Range.

**Comment by azaroth42** [comment]
Regarding readability, the issue (which I still believe is valid) is that in order for a human (e.g. developer) to read through the JSON and see what their client should be doing, they need to constant jump around in the document.  Starting from the top, they jump to the ranges, find the sequence range, then jump back and forth between the list of URIs in that range and some random place in the canvasMap (given that they're not ordered).   Compared to the present layout where you can quite easily read from top to bottom without any jumping around.

We have heard many times a dislike for the xMap pattern in METS, and this is the equivalent in JSON-LD. There's nothing technically wrong with either, it just isn't felt to be as comfortable as a single ordered list.

As to the impact, the cases where there is a positive impact:

* Multiple references to the same Canvas, including the same canvas annotated to others  (rare?)
* Where there isn't a real world ordering to the Canvases, and there might be multiple routes through the set (rare? rare enough we deferred #1238)
* Constructs where the natural order includes only parts of canvases as the view to initialize.  This could include the storytelling case, but also not displaying the color bar/ruler/scanning bed by default but allowing the user to zoom out from the default viewbox defined by the range. (use case is common, data is rare?)
* Multiple sequences with ranges -- it's unclear (per #58!) how ranges interact with multiple sequences at the same time.  (very very rare)

Negative impact:

* Manifest with only a single sequence through the content. There would need to be a map and a range, rather than just a sequence. (very common)
* Readability, as above (very common)
* Socially, it's a huge change compared to the 0.x 1.x and 2.x pattern (ubiquitous)
* If the sequence range can have children (and why not... there could be two sequences with different ranges for different orderings, solving #58) then the client has a lot more work to do to calculate the overall sequence of canvases to render in a thumbnail bar or when next/prev is clicked (uncommon?)

I think the implementation details of template vs building a hash are a wash -- the current pattern is slightly easier for producers (no template issues), of which there are currently many and the code almost always will be custom, and the map pattern is slightly easier for consumers (no need to always construct a hash), of which there are currently not as many and the code can be shared.

**Comment by sdellis** [comment]
We discussed this a bit on the Software Devs call, and although we can see positives for both sides of the debate, as a group we are generally 👎  on the ID Map proposal (sorry @jpstroop !). 

If the goal is to improve Developer Experience, we agreed that it was fairly trivial with existing software libraries to transform a nested hierarchy into a "normalized" data structure that serves similar purposes. "Readability" of the json is a big plus for developers, especially when learning from examples offered in the spec, and ID Maps would certainly hinder readability. On top of it all, it would be a pretty big change, which we'd like to avoid. Basically these are arguments others have made already, but just chiming in from our perspective.

**Comment by yulgit1** [comment]
One perspective maybe determining scope?  Does a canvas exist outside of a sequence, range (or manifest or collection for that matter) for inclusion anywhere within.  Canvases are URIs and the presentation API is an arrangement of URIs.  When you assert a canvas URI for instance, are you asserting a complete unit (with image and other annotation bound for shipment), or a space that can mean different things depending on what is being painted on it. Whats use is its reuse?

**Comment by cubap** [comment]
I am sorry that I have missed this conversation and the call yesterday. We have collided with sequences a lot in our work and the proposals here are compelling. For what it is worth, collapsing congruent items on each other (ranges and sequences) always makes sense to me from a readability perspective. That is, if sequence is a special kind of range that ought not nest, tell me so within the `Range`, instead of changing the vocab. Two serious effects are in dereferencing and ordering.

P2 requires the _all_ the canvases in the sequence to be dereferenced, which makes sense in most deliveries, but really breaks examples like satellite photos and dynamic collections addressed in the [Curation API](http://codh.rois.ac.jp/iiif/curation/index.html.en) as well as the "photos of rooms" example above. The further we get from rendering ordered collections or books, the less sense it makes. An id map doesn't fix this, but the consideration of sequences as ranges might help.

Secondly, all the arrays in IIIF (including sequences and ranges) are `@list`s by default. This is handy when it is true (the default intention of `Sequence`, for example) but is misleading when it is not. This semantic pollution is not fixed either by the recommendations here (even `Collection` is a list, though it rarely ought to be), but if the changes are being considered, there is an opportunity to describe an array as a `@set` instead, reserving `@list` for terms where order must be enforced.

Just saying these things out loud while everyone is talking.

**Comment by zimeon** [comment]
@cubap -- I think your https://github.com/IIIF/api/issues/1072#issuecomment-364176773 comes down as a `-0` on IdMaps specifically? Am I interpreting correctly?

**Comment by cubap** [comment]
@zimeon You are right (unless -0 is an emoticon I don't know). I think the conversation in the meeting probably went the right way, from what I've seen. I just missed a chance to bring up my related pain points while the car was on the lift.

**Comment by jpstroop** [comment]
I wonder if this should be broken into two parts: 1) Collapsing sequences into ranges and 2) id maps

**Comment by jpstroop** [comment]
@IIIF/editors agree close this and focus on collapsing Sequences into Ranges in #1407
