### ISSUE TITLE
Best practices for version transition strategies

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1108]
In the transition period between major versions, having a recommended set of best practices would help to encourage the adoption of the new version without fear that either the client or server implementations are too far out in front of the rest of the community.

A set of possible mitigation strategies should be discussed and a best practice note published once the community has reached consensus.

(Reframed from content negotiation for different presentation API versions)

**Comment by azaroth42** [comment]
Discussion on AV call 08/22:  Doesn't really help backwards compatibility of the viewers, if the 2.x isn't available.  Thinking about migration path, but conneg as the strategy seems like a last resort. Should explore different options. 

AV group proposes to reframe the issue to be about migration strategies within the community, rather than a specific (complicated) technical solution.

@azaroth42 will reframe before Toronto unless objections.

**Comment by azaroth42** [comment]
@srabun @tomcramer The proposal from the AV group was to discuss this as part of the plenary session at Toronto, and thus likely in the road-mapping session.

**Comment by tomcrane** [comment]
Slack Discussion 2018-02-15:

aisaac [3:33 PM]
Hi everyone, a quite naive question: has anyone here had the need to serve manifests both for v2.1.1 and v3.0 for the same images? And if yes how have you handled it?

andyirving [3:47 PM]
not yet, but i'm planning to

azaroth42 [3:58 PM]
We plan to as well

aisaac [4:00 PM]
@andyirving @azaroth42 sounds good but if it’s at planning stage, I guess you don’t have a design/spec that I could look at :wink:
that would mean more beers next week….

azaroth42 [4:01 PM]
Our current thinking is that we'll serve them from a different URI until v3 becomes better supported in viewers, but redirect if the Accept header is the v3 media type. Then (with some warning) we'll switch the v3 into the current URIs

andyirving [4:03 PM]
almost the same except i have to support 2.1 for 10 years :crying_cat_face:

azaroth42 [4:03 PM]
:`(

aisaac [4:04 PM]
@andyirving well at least here’s a service everyone can trust on the long run :wink:
@azaroth42 this sounds perfect. And discovery-wise it means that clients interested in v3.0 would have to use Accept header, or would you materialize the v3.0 URIs somewhere for them to be seen by clients that don’t do content negotiation? My colleague Hugo and I are currently discussing having them as different isReferencedBy objects (in the Europeana pattern at https://pro.europeana.eu/files/Europeana_Professional/Share_your_data/Technical_requirements/EDM_profiles/IIIFtoEDM_profile_042016.pdf) (edited)

azaroth42 [4:10 PM]
They'd be separate certainly, rather than invisible 200 style conneg

mel.mason [4:14 PM]
@ahankinson has been looking into doing this, also with Accept headers I think

aisaac [4:16 PM]
I guess my question now is whether we should require the client to always do conneg, or if there would be a way for the non-conneg-enabled clients to find what they want. The conneg route seems quite clear to me, but I’m interested to hear what you’d think of being flexible - and how to do that. (edited)

ahankinson [4:18 PM]
joined #technical.

ahankinson [4:23 PM]
I've been implementing the v3 draft, and have used the spec to guide the bits of negotiation. Basically, use the `;profile` extension on `Accept` and `Content-Type` to request v2 (by default) or v3.

```> Accept: application/json;profile=http://iiif.io/api/presentation/3/context.json
< Content-Type: application/json;profile=http://iiif.io/api/presentation/3/context.json```
(edited)
If an `application/json` request comes in, it will also include a `Link` header, but not if it's `application/ld+json` -- this is for both v2 and v3.
Our plan is to support 2.1 by default for "a while" and then when the clients are all up on v3, require conneg for 2.1 and 3 by default.

aisaac [4:32 PM]
thanks @ahankinson! Just to be sure: so in your case conneg will be the only way to find the v3 manifest for now?

ahankinson [4:34 PM]
Yes -- We could do 'poor man's conneg' with an unofficial query parameter (`?format=3`) but we wouldn't advertise that. I'm trying to maintain a consistent URI for the same object, so we won't embed the api param in the URL..

aisaac [4:37 PM]
thanks for the answer everyone - this hopefully saves me quite some more modeling/documentation discussion!

azaroth42 [4:41 PM]
@ahankinson So there would be two manifests with the same URI ... presumably the canvases will also have the same URIs?
manifest documents ... abstractly they're the same, I realize

ahankinson [4:43 PM]
Yes, they will. And they won't change from the current Digital Bodleian implementation.
And yes, the canvases will also be available in v2/v3
Also, sequences and collections.

azaroth42 [4:50 PM]
I guess that helps with continuity of annotations -- they'll simply transfer over

ahankinson [4:55 PM]
Yes; we're also thinking of it in terms of interoperability with our own systems. We want to integrate image views in our Medieval collection, but these are two completely separate systems (Medieval MSS are catalogued in TEI). If we can ensure the URLs are also (permanent) URIs then that minimises the amount of human intervention needed when we update Digital Bodleian.

----
2018-02-16

robcast [10:16 AM]
On the very good idea of using Accept header to negotiate Prezi V2 vs V3 I was wondering where in the spec that will be documented? I couldn't find it in the current Prezi V3 alpha.

ahankinson [10:16 AM]
I was sort of reading between the lines on: http://prezi3.iiif.io/api/presentation/3.0/#http-requests-and-responses

robcast [10:16 AM]
Maybe that technique could also be used for Image API.
Yes, section 6 was the only hit I got for searching "accept*" :wink: Still I think the spec could be more exlicit.

**Comment by azaroth42** [comment]
Closing, moved to IIIF/website#59
