### ISSUE TITLE
Manifests should be able to have 0 sequences

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1146]
MUST a manifest have a sequence?  The answer is not normatively explicit in the documentation, but is implied to be that it must by:

> The first such sequence MUST be included within the manifest ...

But if a Manifest has no sequences, then there is no first such sequence to be included, and hence the precondition fails. 

A use case, similar to #1016, is if we know that an object exists and have metadata for it, but no image content yet as it hasn't been digitized ... do we have to create a Sequence with a Canvas with a bland label and no annotated content ... or can we just leave out sequences and use the Manifest as a carrier for "tombstone" data?

**Comment by workergnome** [comment]
I vote no—I would think that allowing that would be a serious breaking change for consumers of the data, and it also makes this somewhat useless as an Image Presentation API.  I would do the blank canvas in that case.  

This is not a strong opinion, mind you.  Happy to defer it if others disagree.

**Comment by tomcrane** [comment]
I fear that this would encourage a IIIF-Universe of ghosts. It would be tempting to make a manifest for everything in the catalogue rather than only for digitised objects, as you've already got the code to make the `metadata`, `seeAlso` and other non-image-content bits. If you have 10% available as IIIF, you can suddenly go to 100% available as IIIF.

**Comment by glenrobson** [comment]
Thinking about Archives we have examples were only part of them are digitised. Particularly in a WW1 project where only relevant items were digitsied. We're unlikely to go back and digitise the missing bits. Its useful to acknowledge that there are parts of the tree that aren't digital but I think I'd try and do this in the collection which represents the metadata hierarchy rather than link to a manifest that was empty. Ideally I think I would have something in the members with an id which links to the catalogue where users could request a physical copy.

**Comment by tomcrane** [comment]
@glenrobson I made this last year: https://wellcomelibrary.org/service/collections/archives/lightweight

If manifests are leaves, it has a lot of branches with no leaves. So you see the archival descriptions down to the parents of the things that would have been manifests...

https://wellcomelibrary.org/service/collections/archives/AMSGWA/2

So that branch didn't get me far, nothing digitised under here.

**Comment by azaroth42** [comment]
A slightly revised scope for the proposal - allow collections to embed manifests _without_ an `@id` or sequences, just type, label and metadata.  That would give the rendering of the collection the ability to show a placeholder for the manifest without publishing something that could result in a weird discovery experience.

**Comment by workergnome** [comment]
I also think that this is pushing the idea that a manifest is somehow
related to images pretty far.  Currently, manifests MUST have an @id, as
well, which is normative.  I think that if you want to create a
placeholder, you need to have a canvas without an image.



- David Newbury
-----------------------------------
p. (773) 547-2272
e. david.newbury@gmail.com

**Comment by azaroth42** [comment]
@beaudet Do you want to weigh in? Or can we tag this as close wontfix?

**Comment by beaudet** [comment]
I do, but I have to run to catch the train - I'll look tomorrow.

**Comment by beaudet** [comment]
So long as institutions with holes in their digitization can create a collection that is representative of ALL objects, not just those with IIIF resources, I see no need for manifests. That said, since manifests are a container for free-form metadata, all of which is typically available for a non-digitized object, the situation creates an awkward split between storing data in manifests vs links that must be resolved first. Can free form metadata be populated in both the collection AND within manifests?

**Comment by beaudet** [comment]
Clarification : I see no need for manifests with zero sequences.

**Comment by beaudet** [comment]
I can easily imagine clients being built that would support traversal of collections with intermingling of objects with IIIF resources and without.

**Comment by thehabes** [comment]
I also have a use case for 0 sequences.  In our software, our user starts a project with the intention of piecing it together.  They may not necessarily have a canvas at the start, they just want to start a project (which requires an empty manifest.sequences).  Right now, I force the user to have a canvas to start, which complicates a 'Start a Project' scenario.

**Comment by azaroth42** [comment]
Discussion on 7/5 call led to general consensus that any manifest MUST have at least one sequence with one canvas, and that canvas SHOULD (MUST?) have at least one content resource (including image, audio, video, text or other).

**Comment by workergnome** [comment]
I'd be OK with SHOULD for content resources, though I'd prefer MUST.

**Comment by thehabes** [comment]
I would say that canvas SHOULD have at least one content resource.  If it is a MUST scenario, it stops the ability to use a simple holder canvas in cases where none are provided during manifest creation.  If it is MUST, then I MUST always provide a holder image as a resource.  Not a huge inconvenience, but a distinction that affects the workflow.

**Comment by glenrobson** [comment]
I agree that the content resource shouldn't be mandatory for canvases in the general case. We have similar cases to Bryan above where we have manuscripts which has blank pages either because we know there is a missing piece or chose not to digitise but want to express to the user there was a page present. 

We also have other cases where a jp2 is broken and rather than break the manifest by pointing to a broken image service we remove the image content. If you get the manifest later the canvas will still be there but there may then be an associated working image api. 

There are examples of the above in our Journals project: http://dev.llgc.org.uk/wiki/index.php?title=IIIF_Journals#Missing_Pages

**Comment by beaudet** [comment]
Perhaps the spec could provide some guidance / implementation notes to identify cases where having no content resource is deemed an appropriate use vs. say... creating canvases for objects that simply haven't been shot yet.

**Comment by zimeon** [comment]
:-1: in Toronto WG meeting. Agreed to close this and NOT implement: Manifests MUST have 1 or more sequences
