### ISSUE TITLE
Support for color mapping such as inverting colors for negative images

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1161]
@puik (originally posted as comment on https://github.com/IIIF/iiif.io/issues/228) But still, what about inverting colors? Often there are negative images (of for instance glass plates negatives) in repositories and it would be very useful to make the images human readable by inverting these.

**Comment by puik** [comment]
Thank you @zimeon for creating a separate issue!
[Mirador](http://projectmirador.org/demo/) does have **invert** together with some other image manipulation (birghtness, contrast, saturation) options. These are very useful as well, but **invert** seems really fundamental need and it could be one extra **quality** parameter for IIIF.

**Comment by workergnome** [comment]
Hi, all—

I agree this could be a useful feature, but I'm not sure that it is appropriate as part of IIIF.  Mostly because when we start getting into pixel-level manipulations, we end up with a huge, huge number of possible manipulations, and we start describing "photoshop-as-an-API".  

For instance, for some of the use-cases that I've been working on, being able to programmatically blur or sharpen images, or do generic convolution filtering, etc. would be very useful, but describing every possible image processing operation seems overly ambitious.

In my mind, the 'quality' parameter is there to allow a client to ask for tradeoffs between image quality and bandwidth, and adding `invert` into there would open the door to far too many operations.

d I also think that a lot of this does properly exist at the UI level, not at the image server level.
 That said, I could easily see a use to extend the IIIF Image API with a common extension or service that allows servers that understand it to respond appropriately.

**Comment by azaroth42** [comment]
I tend to agree that this is in the photoshop-web-api category ... but what are the use cases other than digitized glass plate negatives?

**Comment by puik** [comment]
I do not really agree that **invert** would be so much different from **gray** or **bitonal** (brightness, contrast manipulation are definitely different already).
Can't really think of other use cases than photographic negatives (although not only glass plate but all kind of negatives) but photographic collections are big and there's more and more of that content available.

**Comment by zimeon** [comment]
Picking up on part of @workergnome 's comment: I note that color or b/w inversion is a size-neutral transformation -- there is no bandwidth to be saved by doing it on client or server -- unlike the case of `gray` or `bitonal`.

**Comment by azaroth42** [comment]
Invert seems orthogonal to color/gray/bitonal ... I might want to invert the colors AND make it bitonal.

**Comment by azaroth42** [comment]
Blocked requiring use cases.  Adding tags.

**Comment by nicolasfranck** [comment]
For simple use cases like "invert" or "grey", I should say yes. For other, any modern browser can do this on the fly. I know: by use of javascript, but let's not forget that all kinds of special manipulations are mostly used in viewers where they are used on images "in place" (like mirador does).

The question should be: do you need an inverted iiif image as a thumbnail in your website?

**Comment by robcast** [comment]
I remember some of the blueprints of the Zuse Archive http://zuse.zib.de/ being inverted blueprint-copies and I added a server-side "invert" feature to digilib. I think in the end the project inverted the source images.
I see an advantage for server-side processing in the case of high-bit-depth images but I would be fine with this being an optional extension.
Is there an example for this kind of extension?

**Comment by azaroth42** [comment]
Community Call of 2018-03-14:  No use cases, easy to do on client, with implementation example in Mirador.  Closing, wontfix.
