### ISSUE TITLE
Painting content/annotations to canvases without all of the dimensions is an error

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1190]
This applies only to when annotated-canvas / or resource is annotated onto base-canvas, **only with the `painting` motivation**.

What should a client do in this situation, and the reverse?

Cases:
 * Base canvas has h,w,d ; annotated canvas has h,w,d = Okay
 * Base canvas has h,w,d ; annotated canvas has h,w = Okay
 * Base canvas has h,w,d ; annotated canvas has d = Okay
 * Base canvas has h,w ; annotated canvas has h,w,d = Error
 * Base canvas has h,w ; annotated canvas has h,w = Okay
 * Base canvas has h,w ; annotated canvas has d = Error
 * Base canvas has d ; annotated canvas has h,w,d = Error
 * Base canvas has d ; annotated canvas has h,w = Error
 * Base canvas has d ; annotated canvas has d = Okay

Edit from Getty AV discussion:  Any attempt to annotate a higher dimension resource onto a lower dimension resource is an error.  In order to accomplish it, a higher dimension canvas should be created and have them both annotated on to that. Requires #1191. Commentary annotations on a canvas are fine with higher dimension resources (eg video _about_ a page, rather than video that represents the page).

To expand the first `Error?` case, this would be when there's a Canvas that has only height and width, because it was intended to just capture an image plus transcription, and then a new Canvas with only duration (as an audio track, with transcription) is annotated on to it ... there's no way to align the audio canvas with the spatial canvas.  Or the second error, switch the two Canvases such that the image canvas is annotated onto the audio track canvas.

The options I think are:

* Make them error states, and require that the base canvas have all of the dimensions that the annotated canvas does
* Clients should infer the additional dimensions to the base canvas from the annotated canvas for the purposes of rendering ; Rob doesn't like this as when you have more than one conflicting annotated canvas (e.g. two different h,w canvases annotated to a duration canvas) then you can't tell which height and width should be inferred
* Other?

**Comment by brion** [comment]
I prefer explicit error states here; inferring dimensions onto the base canvas feels 'magic' and might be even more surprising once 3d etc come around.

**Comment by zimeon** [comment]
Discussed in Getty A/V meeting (with edits to the initial description so date on that is misleading). Repeating agreement comment: Any attempt to annotate a higher dimension resource onto a lower dimension resource is an error. In order to accomplish it, a higher dimension canvas should be created and have them both annotated on to that. Requires #1191. Commentary annotations on a canvas are fine with higher dimension resources (eg video about a page, rather than video that represents the page).

**Comment by jpstroop** [comment]
Toronto WG Plenary: 👍

**Comment by jronallo** [comment]
Is there a way to play only the audio from video bitstreams? Or rather what happens if the canvas has only a duration and you paint on video bitstreams/items? 

If you have a duration-only canvas, what happens if you paint on video items that target the whole canvas? Is this different from what happens when you have a duration-only canvas and paint on video items that explicitly target only the duration of the canvas through a media fragment?

The bitstreams/items do not have any indication of their height and width and so could just be treated as audio items. Also in HTML you can make a video the src of an audio element and it plays the audio just fine without displaying the video.

I agree that if you have a duration-only canvas and you try to target the canvas with a media fragment that includes a `xywh` then it should be an error since the canvas does not have any space for painting on the visual component of the video. What I'm presenting is not that case where you have a clear mismatch between explicit dimensions.

This is instead a question of what happens when you intent to reduce a video to just its duration--to just its audio. Use case is that as a manifest creator I want to use the audio from a video without having to extract the audio and publish the audio files myself, especially since I may not have the rights to redistribute the resource myself. Another use case is a video oral history where the video is boring and so the manifest creator only wants to play the audio.

**Comment by tomcrane** [comment]
Rather than relaxing the rules about mismatched dimensions, could we require that you are explicit about what you are intending, by making the body of the annotation yield just the audio of a video? I don't know what this would look like, some flavour of `SpecificResource` that identifies the temporal content of the linked resource.

**Comment by tomcrane** [comment]
@azaroth42 mentions in Slack discussion "But media fragments don't select for audio-only out of video resources" so we'd need to find a different way of conveying that information. I can see the use case and can think of other film studies and related activities that could require this.

**Comment by workergnome** [comment]
To me this starts feeling like we're trying to work around the lack of an Image API equivalent for AV.  Unless we have a mechanism for addressing specific _streams_ within a bitstream (which we don't, which I think is appropriate) we're technically transforming the AV stream.  Implementing this will still require us to render the video--just to do it invisibly.

I think this is the same as starting to add, say, `Black & White` flags into manifests to work around missing Image API endpoints.

**Comment by jronallo** [comment]
The Media Fragments specification (basic) does mention and somewhat define the `track` dimension and give some examples, it just gives no guidance on how to handle this in HTTP or how to process the values. Some of that guidance is in the advanced version but that never got to recommendation status. 

"The way the user agent retrieves information regarding the available tracks of a particular resource is out of scope for this specification." https://www.w3.org/TR/media-frags/#media-fragment-display 
Is there any reason why we couldn't use the `track` name and specify which values a IIIF client ought to accept/reject? 

The basic specification does give guidance on media fragment servers and the case where you're retrieving audio from a video: https://www.w3.org/TR/media-frags/#media-fragment-servers
Since these are in the fragment hash of course you get back a video even if you're just requesting the audio fragment be played. No transformation of the underlying media is suggested.

If leaving off the w,h dimensions from a canvas isn't the way to play audio from a video, then it will probably be easy enough to game this by saying the canvas is 1pixel wide and high which ought to result in a player which looks like an audio player even if it is still trying to render the video. That seems silly. There's no reason to force the client to do the work to render the video component of the video if it isn't really intended to be used.

I don't think this is as much of an issue as @workergnome suggests. This is a common enough case that it was considered in the media fragment work. There's no transformation needed because the browser handles the case of playing just the audio from a video just fine. As far as the bitstream is concerned this is no different than muting the audio of a video and only rendering the video. This is just a case where you're "muting" the visual and only "rendering" the audio.

So one way forward would be to allow the `track` media fragment on a resource and only allow the values of `audio` and `video` (or both). The other way forward that has been mentioned in this issue is to set a time dimension only on the canvas while still having video items annotated on which would result in creation of just an audio element. How else can we achieve this? And are the use cases sufficient to drive us to find a solution?

**Comment by azaroth42** [comment]
Proposal:  Pull the "how to extract/reference the audio of a video" into a separate issue.  The resolution of this issue, that it is an error to associate mismatched dimensions, would not block that, as only audio would be annotated to a duration only canvas.

**Comment by azaroth42** [comment]
Closing now that @jronallo has created the new issue and the PR is merged. Thanks!
