### ISSUE TITLE
Support track media fragments for A/V in Presentation API?

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1234]
Should we support track media fragments as well as timed fragments in annotations? W3C specs provides means to specify fragments but no formalization for discovery/naming:

  * https://www.w3.org/TR/media-frags/#media-fragment-syntax
  * https://www.w3.org/TR/media-frags/#fragment-dimensions
  * https://www.w3.org/TR/2011/WD-media-frags-recipes-20111201/#rtsp-track

How would a client find out what tracks are called?

Could this be be solved with ranges instead of URI fragments?  Annotating a named part could be a range.

2017-09-05 AV Call: Channel (left/right) use case discussed, but no way to determine what to put in the track parameter of a media fragment without explicit format level information. Defer until there's some real implementations/requirements.

See also use case for [Annotating audio and video channels separately](https://github.com/IIIF/iiif-av/issues/29).

(This issue split out from #807.)

**Comment by brion** [comment]
The media fragments spec is pretty vague, with examples of numerically-indexed tracks... (`#track=1&track=2` to select "both tracks 1 and 2")

The HTML5 spec has a different example, using `#track=Alternative` to select a track labeled as "alternative". https://www.w3.org/TR/html5/embedded-content-0.html#selecting-specific-audio-and-video-tracks-declaratively Note that since audio and video tracks are indexed/numbered separately in HTML5 media, it's unclear what a numbered track would mean...

Would need to test to see what's actually supported across a broad subset of browsers...

Note that tracks can be selected at runtime in the player via the `audioTracks` and `videoTracks` properties: https://www.w3.org/TR/html5/embedded-content-0.html#audiotracklist-and-videotracklist-objects however that will not provide things like left/right channel selection.

**Comment by brion** [comment]
Ok, supposedly the 'id' returned from the tracks is legit for usage of the media fragment, per spec... But nobody implements the track lists anyway except on MSE SourceBuffer. Nevermind. :P

**Comment by zimeon** [comment]
Not going to support in presentation 3.0. Could be added as a minor release if there were later agreement to add support

**Comment by azaroth42** [comment]
I think that this is closed by the resolution of #1332? We can refer to the use-case justified "tracks" now with the new selectors. At the very least it should be use-cases-needed?

**Comment by workergnome** [comment]
Can we?  I think we can refer to audio or video, but not, say, "left-channel" or "french-audio".

**Comment by azaroth42** [comment]
Eds: Close won't fix. We should treat these resources as black boxes rather than trying to extract bits from them. No one has asked for this in the last 7 years, think we're probably okay.
