### ISSUE TITLE
Assess client requirements per class/property

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1243]
As a subset of #76, the Presentation API should at least be consistent in how it describes client requirements.  Currently the requirements are spread throughout the text, making it difficult to know what must be implemented and what can be ignored.

Options for where to put them:
 * Separate "Client Requirements" section to avoid mixing model and implementation
 * In section 3's per property / per class requirements lists
 * Styled callout anywhere they currently appear 

I currently prefer putting them in section 3... thoughts?

**Comment by zimeon** [comment]
I agree that making client requirements clear is helpful -- both for client developers and content creators. I tend toward the section 3 option because I think if one had a separate client requirements section it would end up with a lot of repetition of section 3 anyway (I don't like the callout option as that would break up the doc in a distracting way).

**Comment by jpstroop** [comment]
I'd be OK with section 3, and/or another table in the appendices.

**Comment by mikeapp** [comment]
👍  to section 3

**Comment by azaroth42** [comment]
First cut at the MUST / SHOULD / MAY division:  http://prezi3.iiif.io/api/presentation/3.0/#resource-properties

**Comment by azaroth42** [comment]
AV call: Looks good, add tables in appendix for client requirements.

**Comment by azaroth42** [comment]
Closing, editorial agreement to put it in section 3. New issue to be opened to validate the actual requirements.
