### ISSUE TITLE
Manifests cannot reference other Manifests

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1251]
Use Case:  There are two manifests that describe the same object, but are constructed to have different labels and metadata for a different set of audiences.  For example an art historian or conservator would want to have a different description of a painting compared to the public.  It would be useful to create links between these manifests to allow users to navigate and select which one they're interested in, and for discovery solutions to index them together.

There are currently 4 ways to reference external resources, none of which allow for this situation:
* `related` must be able to be displayed to the user
* `rendering` must be able to be displayed to the user
* `service` describes additional functionality, not an additional description
* `seeAlso` requires that the target resource *semantically* describe the manifest/object ... and Presentation API resources are inherently not semantic.

So do we change the definition of one of the existing properties, and if so which/how, or do we add a new relationship?

**Comment by jpstroop** [comment]
A linking property that maps to dc:alternative seems like an obvious
solution, but I wonder if we could expand/bend the definition of one of our
existing properties.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

On Sep 18, 2017 7:23 PM, "Rob Sanderson" <notifications@github.com> wrote:

Use Case: There are two manifests that describe the same object, but are
constructed to have different labels and metadata for a different set of
audiences. For example an art historian or conservator would want to have a
different description of a painting compared to the public. It would be
useful to create links between these manifests to allow users to navigate
and select which one they're interested in, and for discovery solutions to
index them together.

There are currently 4 ways to reference external resources, none of which
allow for this situation:

   - related must be able to be displayed to the user
   - rendering must be able to be displayed to the user
   - service describes additional functionality, not an additional
   description
   - seeAlso requires that the target resource *semantically* describe the
   manifest/object ... and Presentation API resources are inherently not
   semantic.

So do we change the definition of one of the existing properties, and if so
which/how, or do we add a new relationship?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/IIIF/iiif.io/issues/1251>, or mute the thread

**Comment by glenrobson** [comment]
Do they describe the same iiif image? 

Would people be able to link to copies of the same work (put different physical objects) using this field or would you restrict it to the same IIIF image or Images? 

Would this fit the derivative use case where somebody adds a table of contents to a manifest and references the original?

**Comment by tomcrane** [comment]
We have this scenario, where we have alternative versions of the manifest that have in-progress OCR-generated annotations and tagging. 

I don't think any current linking properties could be bent far enough to be used for linking to a resource that describes the same object, as IIIF, while still doing their (required) current jobs.

**Comment by jpstroop** [comment]
> I don't think any current linking properties could be bent far enough to be used for linking to a resource that describes the same object, as IIIF, while still doing their (required) current jobs.

👍  I agree.

**Comment by mikeapp** [comment]
👍  in general.

**Comment by azaroth42** [comment]
Ed's proposal:  Use `seeAlso` given the discussion about service vs seeAlso in #1269. As the "semantically describes" requirement goes away, we can just do:

```
{"seeAlso": [
  {
    "id": "http://example.org/iiif/target/manifest.json",
    "type": "Manifest",
    "label": "Drawing precursor to this Painting"
  }]
}
```

**Comment by azaroth42** [comment]
Ready: http://prezi3.iiif.io/api/presentation/3.0/#seealso

**Comment by tomcrane** [comment]
I think we should try to standardise the language used for _the resource that has the property_ for the linking properties.

Currently:

> **related**
> A link to an external resource that describes or is about the IIIF resource.

> **seeAlso**
> A link to a machine readable document that is related to the resource with the seeAlso property

I know that last one has been there for a while but it is confusing to parse; it could be:

A link to a machine readable document that is related to the IIIF resource

**Comment by azaroth42** [comment]
:+1: This is blocked by the changes in #1302 being accepted. (hinty mchint hint)

**Comment by azaroth42** [comment]
The resource that has the property is now issue #1322. Close?
