### ISSUE TITLE
What should clients do with text annotations `painting` the entire canvas?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1256]
Is there something that can be recommended for rendering text associated with the entire canvas (perhaps for a limited duration) but not with any x,y,w,h?  Could provide implementation guidelines -- e.g. don't stretch the text over the entire canvas, unlike an image.

Comes from AV discussion, but applies to pure image canvases as well.

**Comment by brion** [comment]
Distinct motivations for 'caption/subtitle' versus 'title' perhaps? It's common to want to overlay title cards on top a video which you wouldn't want shown subtitle-style, as well.

**Comment by azaroth42** [comment]
It would need to be expressed in terms of functionality, as "caption" is a semantic notion not a presentation notion.

**Comment by azaroth42** [comment]
More specific case of #1257.

**Comment by azaroth42** [comment]
Impacts / would potentially be solved by further more specific painting motivations, such as 'transcribing'.  See #511.

**Comment by mkanzaki** [comment]
Test 51 of the fixtures (Embedded Comment on a Canvas) seems to be this case. My tool renders it as "Page Info" bellow the canvas, like a description of a canvas (with a small annotation mark). http://www.kanzaki.com/works/2016/pub/image-annotator?u=http://iiif.io/api/presentation/2.0/example/fixtures/51/manifest.json
Could be a part of side panel.

**Comment by tomcrane** [comment]
This issue is not precisely named enough. The question concerns annotation with the `painting` motivation only, where the instruction to the client software is that the content should be rendered **on the canvas**. In test 51, the motivation is `commenting`, e.g., "This is an early example of chiaroscuro". So @mkanzaki's example is correct. If the annotation (http://iiif.io/api/presentation/2.0/example/fixtures/list/51/list1.json) had the motivation `oa:painting`, the example would be wrong - the text "Comment" should appear in the canvas area indicated by the purple box. The question is- should it be stretched to fill the box, or should it flow from the top left, or top right etc (determined by info on viewingDirection, if available), or what? 

My suggestion is that the spec is silent, let the client decide. If it were my viewer, I'd have a standard font size and start the caption top left (if ltr), letting it flow. The end user could increase the font size either directly through browser control, or via the client software if it offered UI to scale text annos (familiar accessibility controls). The behaviour would be identical to how @mkanzaki and @OpenHypervideo and I have all done it in AV demos for the "Fire" example - e.g., http://www.kanzaki.com/works/2016/pub/image-annotator?u=https://tomcrane.github.io/fire/manifest3.json&moreviewer - but with the absence of specific `#xywh=...`, the box is the whole canvas. None of us thought to scale the text in the box to fit, I wouldn't change that just because the target is the whole canvas.

**Comment by azaroth42** [comment]
I think we can close the issue? The current definition is correct -- a painting annotation targeting the entire canvas should paint the content over the entire canvas. See #1258 for the issue for making this less stupid in the case where we have transcription style content.

**Comment by tomcrane** [comment]
:+1: to close, agree that `transcribing` as a spec-blessed motivation makes it go away (leaves it up to implementations to do sensible things).

**Comment by mikeapp** [comment]
👍 to close

**Comment by azaroth42** [comment]
A week of open-ness. Closing in favor of the actionable #1258.
