### ISSUE TITLE
Can context be modified to generate unquoted integers/floats from RDF?

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1291]
Discussion at Toronto WG agreed to #1252 such that quoted integers/floats are not allowed. It was asked whether it might be possible to adjust the context to generate JSON-LD from RDF in a way that does not quote the types values. There was agreement to consider a change in the context if this is possible.

**Comment by mixterj** [comment]
Yes, properly generated RDF statements described as an integer will re-serialize as JSON-ld without quoted numbers.

Here is a set of triples:

`<http://example.org/Person/1> <http://example.com/name> "Jane Doe" .
<http://example.org/Person/1> <http://example.com/jobTitle> "Professor" .
<http://example.org/Person/1> <http://example.com/age> "8"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://example.org/Person/1> <http://example.com/telephone> "(425) 123-4567" .
<http://example.org/Person/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .`

Here is the resulting JSON-ld:

`{
  "@context": {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "http://schema.org/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@id": "http://example.org/Person/1",
  "@type": "schema:Person",
  "http://example.com/age": 8,
  "http://example.com/jobTitle": "Professor",
  "http://example.com/name": "Jane Doe",
  "http://example.com/telephone": "(425) 123-4567"
}`

You can test it here: http://rdf-translator.appspot.com/

**Comment by christopher-johnson** [comment]
Note: the above result occurs when the json-ld processor option flag called "[use native types](https://json-ld.org/spec/latest/json-ld-api/#overview-15)" is set to `true`.  The [default is `false`](https://github.com/digitalbazaar/jsonld.js/blob/3f0ad206db4e863222765e4289fe756b3f80d753/js/jsonld.js#L850)

**Comment by christopher-johnson** [comment]
ref #1272

**Comment by workergnome** [comment]
That seems like a useful thing to add to the spec as an implementation note.

**Comment by mixterj** [comment]
I think the above example will work regardless of whether the 'use native types' is set to `true` or `false`. The 'use native types' setting is really important if you are working with data that is not xsd classified in the data but if you have properly formatted RDF data that explicitly types the integers as xsd:integers, the json-ls processor should not have problems. I am not an expert on JSON-ld processors but the spec seems to suggest that issues mostly arise when the processor is left with trying to determine the datatype (i.e. not encoded in the data). If that is the case, the real problems arises when you are using an RDF serialization like Turtle where the semantics of the value are typically encoded by the structure (i.e. 8 vs 8.4 vs "8"). Unless you are very verbose in the Turtle and explicitly declare values as xsd:integer, serializing to JSON-ld can lead to problems.

I say this only because I was using the Python's [rdflib-jsonld](https://github.com/RDFLib/rdflib-jsonld) module and it also assumed that 'native types' is [false](https://github.com/RDFLib/rdflib-jsonld/blob/master/rdflib_jsonld/serializer.py) and I did not have any problems.

**Comment by christopher-johnson** [comment]
That seems like a bug in that library, possibly related to the internals of Python that cast primitives without requiring explicit declarations.   If you paste the RDF example in the [Ruby Distiller ](http://rdf.greggkellogg.net/distiller)
```json
{
  "@context": {
    "schema": "http://schema.org/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@id": "http://example.org/Person/1",
  "@type": "schema:Person",
  "http://example.com/age": {
    "@value": "8",
    "@type": "xsd:integer"
  },
  "http://example.com/jobTitle": "Professor",
  "http://example.com/name": "Jane Doe",
  "http://example.com/telephone": "(425) 123-4567"
}
`´``
This is the result

**Comment by mixterj** [comment]
So if you set 'use native types' to true you get the json-ld with JSON numbers? If so, then I agree it is a problem with the Python module, though I do not think it is an inherent pythonic issue. My guess is that it is a problem in the serialization code not conforming to the JSON-ld spec.

Also, some might consider it a 'feature' and not a 'bug' ;)

@zimeon If I recall, you are a Python guy, could you let me know if you encounter this with whichever Python RDF module you use?

**Comment by azaroth42** [comment]
Try PyLD.  rdflib-jsonld is indeed buggy and incomplete.

**Comment by azaroth42** [comment]
Given that the native types flag is an implementation detail, not part of the context, the answer to the question is ... no, we can't.

Closing.
