### ISSUE TITLE
Consider size of Annotation Pages

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1340]
[Annotation Pages](http://prezi3.iiif.io/api/presentation/3.0/#annotation-pages) for things like fine grained OCR, especially with language information, quickly grow to large sizes. Much of the problem is a great deal repetition in each expanded `body`. Are there any strategies we might use to make the JSON-LD representation compact?

This issue was raised by Valentine on behalf of @hugomanguinhas during the IIIF workshop at SWIB17.

**Comment by zimeon** [comment]
Annotation for a single word in French using the compact fragment syntax (cf. #1335) might be:

```
{
      "id": "http://example.org/anno1",
      "type": "Annotation",
      "body": {
        "type": "TextualBody",
        "value": "Il",
        "language": "fr"
      },
      "target": "http://example.com/c/canvas1#xywh=11,22,33,44"
    }
```

**Comment by zimeon** [comment]
I think what we'd really like is a way to avoid all the repetition by saying things along the lines of "all of these annotations have French bodies". I don't see a way to do such a thing in a resource-centric / JSON-LD / RDF fashion... but raising the question in case others do.

**Comment by hugomanguinhas** [comment]
Hi Simeon, Rob,

Thanks Simeon for creating this issue!

... we are presently implementing the IIIF Presentation API (v3) to power our new Newspapers Thematic Collections, which we would like to deliver word-level full text. Since much of our full text is language tagged and in most cases, it is the same within one issue, we would like to find a way to minimize the response given that attaching a language to each word would at least double its size, not forgetting the need to construct a body object when it could be avoided.

Since it is a best practice to group the annotations in an Annotation List, we were considering an option to associate a language property to it to act as a default when no language information is associated to the body of the annotation. Actually, ALTO also allows for the language to be associated with different levels of the text structure, such as TextBlock, TextLine, etc.

Cheers, Hugo

**Comment by azaroth42** [comment]
I don't think this is solvable in a way that's consistent with Linked Open Data. LOD is verbose due to the open world nature, everything is associated with the resource directly not via one of many containers that it could be part of.  We explored this exact issue in the Open Annotation work, and then discussed it during the Web Annotation work ... the format is intentionally not optimized for compactness, rather for expressiveness. 

As per the discussion in #754, there are an infinite number of "summary" style properties that might be applicable for these sorts of scenarios.  As per #754, I propose `close wontfix` ... it's not possible to solve.

**Comment by hugomanguinhas** [comment]
Hi Rob,

Thanks for your answer...

Following your comment about "the format is intentionally not optimized for compactness, rather for expressiveness", I wonder if the rationale behind not having the provenance information associated to the Annotations both the ones that display the page images and the ones for full text is not the same.... we are basically talking about implicit versus explicit information, where the implicit information could be obtained from different "sources" which is a common practice in information modelling (ontologies)... you dont need to materialize all information...

Cheers, Hugo

**Comment by azaroth42** [comment]
Indeed, but the scope of possible computable/inferable properties is (literally) infinite and in practice impossibly large.  Per #754, if we opened the door for (say) language of the body of the annotation to be recorded on the AnnotationCollection and then all annotations somehow inherit it, then the door is open for all of the other possible ways to group annotations.

I'm still a strong :-1:

**Comment by zimeon** [comment]
Agreement on editors call that there is no acceptable solution for this in JSON-LD 1.1 and thus we can't have a more compact syntax in presentation 3.0. Marking `defer`.

**Comment by azaroth42** [comment]
Eds agree: no possible solution in the foreseeable future, so closing wontfix.
