### ISSUE TITLE
produce and document v2-v3 converter

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1344]
As we will doubtless have v2 manifests around for a long time, a converter than can auto-upgrade (at least as much as possible) a v2 presentation api resource to v3 would be very valuable for managing the transition period.  It could have two forms, like the validators, a service that either retrieves or accepts a POST of the data to transform, or a library that can be included into other software.  Unlike the validators, multiple implementations in different languages according to a common specification would be very useful.

I believe, to date, the changes are:

### Property Renaming
- [ ] @id -> id
- [ ] @type -> type
- [ ] startCanvas -> start
- [ ] contentLayer -> includes
- [ ] * -> items (with special cases)
- [ ] otherContent -> annotations (broadly)
- [ ] description -> metadata pair, or summary (flag?)
- [ ] license -> rights
- [ ] viewingHint -> behavior
- [ ] related -> homepage
- [ ] on -> target
- [ ] resource -> body
- [ ] full -> source
- [ ] style -> styleClass

### Enumerated Values
- [ ] All classes to lose sc:, oa: prefixes
- [ ] AnnotationList -> AnnotationPage
- [ ] Layer -> AnnotationCollection
- [ ] motivation to lose sc:, oa: prefixes
- [ ] update context to 3
- [ ] profiles -> short profiles
- [ ] embedded contexts -> types

### Values
- [ ] languageMaps instead of @language/@value
- [ ] arrays everywhere
- [ ] {id: x, type: y} instead of "x"
- [ ] ContentAsText to TextualBody

### More complicated stuff

- [ ]  Determine which annotations on a Canvas should be items and which annotations
- [ ] Try to add type to content resources
- [ ] Unflatten Ranges

### Minimal Validity

- [ ] A Collection must have at least one label.
- [ ] A Manifest must have at least one label.
- [ ] An AnnotationCollection must have at least one label.
- [ ] id on Collection, Manifest, Canvas, content, Range, AnnotationCollection, AnnotationPage, Annotation
- [ ] type on everything
- [ ] width+height pair for Canvas, if either
- [ ] items all the way down

I would propose to write one in Python with the help of (hopefully) @zimeon and @glenrobson, and then have someone translate into idiomatic javascript.

**Comment by tomcrane** [comment]
Yeah, I've been mulling this for some time. It's an easier dev experience to target P3, because of the consistency and predictability fixes, so the obvious route for people writing a new viewer would be to target P3 only and include this library to convert anything that isn't.

Where it gets tricky is in links to auth, search, anno lists etc.

Happy to collaborate on Python and JS versions.

**Comment by zimeon** [comment]
Also happy to collaborate on Python version at least

**Comment by azaroth42** [comment]
To avoid hammering the master issue list with micro tasks, how about:
--> https://github.com/iiif-prezi/prezi-2-to-3 

And close this?

**Comment by sdellis** [comment]
I agree with @tomcrane that future viewers should try to convert and present v2 manifests using the JS library. Can I suggest that the JS version be written in Node/Typescript as an isomorphic library and distributed as a npm package? This would make it very easy to import into future clients and servers alike. Happy to collaborate on that version if need be.

**Comment by workergnome** [comment]
It might be worth conflating this with some of the discussions about computational validation for IIIF JSON.  If there's interest in, say, TypeScript, it's probably worth defining the types in JSON Schema and converting to Typescript, so that other libraries can use the data model.

Validation will be important, since we can't control what JSON the client shoves at us, and it's going to be useful to provide feedback as to both what parts are incompatible with V2-V3 and what parts are incompatible because they're incorrect.

**Comment by azaroth42** [comment]
Closing this as it's now IIIF/prezi-2-to-3
