### ISSUE TITLE
Move above level 2 features into extensions?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#1376]
Cf. #1374 

Given that we aspire to build a registry of extensions, should we move description of any completely optional (i.e. above level 2) features into the extension registry? They could have a separate context or even no context and just minted URIs.

**Comment by zimeon** [comment]
From http://iiif.io/api/image/2.1/compliance/ we have the following as optional at all levels:

  * `square` - becomes mandatory at level1 in Image 3.0
  * `max` - becomes mandatory at level0 in Image 3.0
  * `sizeAboveFull` - removed entirely in Image 3.0
  * `rotationArbitrary`
  * `mirroring`
  * formats `tif`, `gif`, `pdf`, `jp2`, `webp` 
  * `profileLinkHeader` remains _MAY_ in Image 3.0
  * `canonicalLinkHeader` remains _MAY_ in Image 3.0

**Comment by zimeon** [comment]
I do not think we should introduce and new feature that are optional at all levels. However, I think we should leave the current ones rather than removing to an extension -- this seems simpler to understand,  and `rotationArbitrary`, `mirroring` and extra formats are already widely implemented (even if little used)

**Comment by workergnome** [comment]
Could perhaps a compromise be to create a 'extension' context and page for them, but include that context into the default context?

or is that just the worst of all worlds?

**Comment by zimeon** [comment]
If the existing extra formats (`tif`, `gif`, `pdf`, `jp2`, `webp`) were already included in a registry of extensions (and the registry linked from the formats section in the spec), it would seem harmless to move these out. We'd only get rid of 5 table lines in spec and compliance docs, but it would reduce a rather arbitrary list to the 2 we usually care about (`jpg` and `png`)

**Comment by workergnome** [comment]
I'd like that, in that it begins to demonstrate the registry (which is hard to explain when it's entirely empty.)

**Comment by azaroth42** [comment]
Meh. -0.5 ... if they're not in the spec, we will constantly get questions about why we no longer support tiff.  I'm in favor of closing the issue, won't fix. There's tons of optional stuff in specs... but they're in the specs.  Just because we have a particular hammer (extensions + registries) doesn't mean that we need to use it to beat all nails into submission.

**Comment by azaroth42** [comment]
Eds meeting, community call: Won't Fix -- confusion added is greater than confusion removed by doing it.
