### ISSUE TITLE
Support canvases sharing time dimension (master clock) but not spatial dimension

### ISSUE THREAD

**Issue by jwd** [IIIF/api#1378]
Need to be able to present multiple canvases that are coupled in time dimension but not spatial dimension. For example, presenting a video of a dance performance and image of the corresponding musical score in two separate windows, with textual annotations referencing a spatial segment of the score canvas (e.g. a measure) and time segments of the video. Client needs to be able to allow independent resizing, moving, closing/hiding of canvases.

From discussion on 2018-02-06 AV call ([see notes](https://docs.google.com/document/d/1gawDtScHt6Q_D3uBbyLGOUHWwhh_5qMFMGXX4dRnxpA/edit?usp=sharing)). Need to explore whether this is possible with Presi 3.0 draft spec. If not, may be out of scope for 3.0.

**Comment by azaroth42** [comment]
In 3 we have a distinction between transcribing and painting, where transcribing annotations can be repositioned: http://prezi3.iiif.io/api/presentation/3.0/#values 

There could be a master canvas to have the master clock, but then the component canvases are `transcribing` rather than `painting` on to it.

**Comment by jwd** [comment]
As per comment above by @azaroth42 and discussion at BL AV meeting on 21 Feb 2018, it appears this can be handled via annotations using the transcribing motivation rather than painting. See also https://github.com/IIIF/api/issues/1443
