### ISSUE TITLE
sequence ranges may or may not have structure

### ISSUE THREAD

**Issue by jronallo** [IIIF/api#1489]
One assumption some have had with https://github.com/IIIF/api/issues/1417 is that a "sequence" range ought to be flat. 

I raised on the community call (https://docs.google.com/document/d/1XcXXrer42a3wGgvJpDgA2PQSo9MmO0e8PvuamWlRWiw/edit) that it may be nice to only maintain a single range that includes both structure (TOC) as well as the preferred sequence. Having to maintain both a sequence range as well as a structured range that include the same sequence of canvases seems like it could seem like needless duplication and additional effort to maintain.

There were some questions that were raised during the call about allowing the combining of sequence and structure in a single range. What happens to a sequence when a range ends at the middle of a page and the next range picks up on the second half of the page? Does collapsing into whole canvases happen for creating the sequence to display (say in a thumbnail strip)? How do you know the intention?

Further, if a sequence range must be flat does it also follow that the list of items on a sequence range must also only target whole canvases? Or can a sequence range duplicate a canvas by referring to a fragment? Are these sequences of whole canvases or potentially sequences of fragments of canvases?

**Comment by azaroth42** [comment]
I don't think that a sequence with hierarchy is a deal breaker, though it does make it more complicated to find the order.  Probably a best practice to have it flat so that clients can quickly present the first canvas and a thumbnail navigation bar.

The parts of Canvases however leads to ambiguous situations, and hence must be avoided.
For example:  The sequence might be intended as the regions of the canvases that contain the depiction of the book pages, and not the scanner bed, ruler, color strip etc... however they're still present in the image and thus in the canvas area. In this case it would be incorrect to expand to the entire canvas.  On the other hand, the textual structure of the content is very likely to require partitioning of the same canvas ... which should not be different thumbnails in a navigation bar, or worse, separate views entirely.

**Comment by azaroth42** [comment]
Eds' call:  Rob to make concrete examples demonstrating the two sides of the parts issue; then discuss on 3/14 call.

**Comment by azaroth42** [comment]
Community Call on 2018-03-14:  

* Recommend "a small number" of levels of nesting of ranges.  Possibly 5, 6 (H1-H6) or 10 ... possibly indeterminate.
* No objections to sequences with hierarchy.

* Agreement that color bar removal is a very real use case, and hence should allow fragments in ranges.
* Must be what is expected to be the full view of the content, which might be less than the entire canvas.  e.g. don't feed in the top part of a page as end of chapter into your page turner.
* Simplifies number of ranges to maintain.

**Comment by azaroth42** [comment]
Closed by #1508
