### ISSUE TITLE
IIIF JSON-LD patterns and external specs

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#1515]
From pull #1510 we have the principle

> #### 3.4.1. Always Use Arrays for Multiple Value Properties 
> If a property can ever have multiple values, it will always be an array even if it has only one value. This means that code can always iterate over the values without checking first to see if it's an array.  Thus we use `"language": [ "en" ]` and not `"language": "en"`.

https://github.com/IIIF/api/pull/1510/files#diff-5e2e11585f5945b5b9c59190b0a2fc4aR157

In Presentation API section 5.6 there's an example annotation, that includes this:

```
  ...
  "type": "Annotation",
  "motivation": "painting",
  ...
```

Now, `motivation` is not from the IIIF spec - but when when serialised in a IIIF representation, should it follow 3.4.1 and be `"motivation": ["painting"]`?

**Comment by azaroth42** [comment]
I don't think we should reformat external specs' JSON-LD, and thus I think it stays as a string rather than a singleton array.

My reasoning:

  * We don't know the context or infrastructure that the content is generated in / managed by and whether that infrastructure can generate the array. We thus shouldn't make requirements that go beyond the requirements of the external spec if we expect to use non-IIIF infrastructure.
  * The context of the external spec should have `@container:@set` if the array form is required (and similar for other structures).  For `@set` it seems relatively easy, but consider `label` as a language map vs `label` as an array of values.
  * We did this in 2.1 by redefining the context for annotations ... and it was a painful mistake.
  * With JSON-LD 1.1, we can scope contexts in based on classes and thus ensure that the right context is in effect without the implementer needing to worry about it.  They just need to know the structures that are possible.

So I'm in favor of close, no change.

**Comment by zimeon** [comment]
Maybe the "no change" action is the addition of a sentence of clarification to the new section 3.4 in design principles saying something along the lines of "These conventions apply only to content structures defined by IIIF specifications, no additional restrictions are placed on content included in accord with external specifications."

**Comment by tomcrane** [comment]
Mention `motivation` specifically in the spec? As it may be a particularly prominent tripping up point.
