### ISSUE TITLE
rename Search API to Annotation Search API or similar

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1628]
Especially given the discovery work, it would be good to disambiguate searching manifests from searching annotations.

(cc @aisaac)

**Comment by tomcrane** [comment]
I agree with the disambiguation, but I have one concern - the word Annotation really only controls how the results are returned, rather than what is actually being searched to generate those results. 

A search API endpoint on a collection could return free text results across all the works in that collection, in the form of annotations, but it's unlikely to be searching annotations on the server to do that. So the rename might replace one confusion about what you can use it for with another.

Content Search API <=
Search Within API

As opposed to

Search for a thing API
Discovery API

I'm +1 on disambiguation, +0.2 on this solution to it.

**Comment by aisaac** [comment]
I won't fight for the currently proposed name for long. But still the current spec does say that annotations are what is being search to generate the results: http://iiif.io/api/search/0.9/#2-overview .

**Comment by aisaac** [comment]
@jbhoward-dublin this is right, but then we should consider this to all wording, including the current one. "Search" (used alone) brings much more harmful misunderstandings in our community than "annotation search" would.

**Comment by azaroth42** [comment]
Done :)

**Comment by zimeon** [comment]
We use "Content Search API" consistently now
