### ISSUE TITLE
Clarify if multi-part collections can have sub-collections

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1633]
Should a collection with the multi-part behavior only be valid when the collection does not have any sub-collections, as implied by the documentation?

**Comment by sdellis** [comment]
Can you elaborate, @azaroth42 ? I was just talking with some colleagues yesterday about representing Journals as multi-part collections (comprised of Volumes) with sub multi-part collections (comprised of Issues). Existing viewers don't currently support this, but there's no reason they couldn't, unless there are other issues you foresee with this approach.

**Comment by glenrobson** [comment]
I'm also not sure why multi-part collections can't have sub collections. This was a hierarchical archive I converted while at NLW which was modeled as multi-part all the way from the top collection down. The example below is level 2 and contains links to manifests + sub collections:

http://dams.llgc.org.uk/iiif/archive/3975658/vtls005019642/series.json

Individual manifests e.g. 'Enclosures removed from CTB2/2/1 comprising correspondence relating to expense claims' make no sense on their own with out their collection context. We were hoping to get the clients to 'Clients might render the collection as a table of contents, rather than with thumbnails.' as mentioned in the 2.1 spec. For info here is the top collection:

http://dams.llgc.org.uk/iiif/archive/3975658/fonds.json

**Comment by azaroth42** [comment]
Edited to repurpose to a discussion. Was mostly transcribing from the AV call this morning :)

**Comment by jpstroop** [comment]
From 18 July editor's call: if anything, it seems like `multi-part` Collections are more likely to have sub-collections than those that are just a group of Manifests. Propose that we not change any semantics, but tighten up the definition of `multi-part` to read as follows:

> Valid only on Collections. Collections that have this behavior consist of multiple Manifests or Collections which together form part of a logical whole or a contiguous set, such as multi-volume books or a set of journal issues. Clients might render the multi-part Collections as a table of contents rather than with thumbnails, or provide viewing interfaces that can easily advance from one member to the next.

**Comment by azaroth42** [comment]
Community call of 2018-08-01: Agree that multi-part collections can have sub-collections.

**Comment by azaroth42** [comment]
Closed by #1650

**Comment by zimeon** [comment]
Approved by TRC, already merged into `image-prezi-rc2`.
