### ISSUE TITLE
Internationalized homepages require 0-n entries, currently 0-1

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1759]
Issue raised in Edinburgh about the cardinality of `homepage` and how to have homepages for different languages.

The homepage is an external resource, so can have the `language` property, but there can only be one homepage. Thus it is not legal to do:

```
  "homepage": [
    {
      "id": "https://example.org/en/homepage",
      "language": ["en"]
    },
    {
      "id": "https://example.org/de/homepage",
      "language": ["de"]
    }
  ]
```

Which is the only way to accomplish this (rather obvious) use case.

Propose that we make `homepage` an array of JSON objects instead of a single object.

**Comment by zimeon** [comment]
I agree that we should probably do this. Ideally the homepage would be internationalized but conneg or such but that is not always done/available and might lead to results inconsistent with viewer locale/language selection based on some other means (like explicit selection in the app).

Related, should we add a new [design pattern](https://iiif.io/api/annex/notes/design_patterns/) along the lines of -- _**Design for Worldwide Use**: IIIF specifications should support text values to be displayed to users in any language and with the option of multiple languages in order to support use around the world._

**Comment by mikeapp** [comment]
👍

**Comment by tomcrane** [comment]
:+1: to the original issue

**Comment by zimeon** [comment]
still :+1: on original issue

**Comment by jpstroop** [comment]
👍

**Comment by zimeon** [comment]
Approved and PR merged. Closing.
