### ISSUE TITLE
URL signing

### ISSUE THREAD

**Issue by verglor** [IIIF/api#1775]
Image API should support URL signing to prevent [URL tampering](https://thumbor.readthedocs.io/en/latest/security.html#url-tampering).

**Comment by jpstroop** [comment]
I'd say, generally speaking, that this is a feature, not a bug--and something that clients implementing [compliance level 2](https://iiif.io/api/image/2.1/compliance/#size) need to be prepared for; they can return a [503](https://iiif.io/api/image/2.1/#table-of-contents) if necessary.

FWIW, The Image API does have [optional features for limiting the size of an image request](https://iiif.io/api/image/2.1/#profile-description):
> The maxWidth, maxHeight and maxArea parameters provide a way for image servers to express limits on the sizes supported for the image. If maxWidth alone, or maxWidth and maxHeight are specified then clients should expect requests with larger linear dimensions to be rejected. If maxArea is specified then clients should expect requests with larger pixel areas to be rejected. The maxWidth / maxHeight and maxArea parameters are independent, servers may implement either or both limits. Servers must ensure that sizes specified by any sizes or tiles properties are within any size limits expressed. Clients should not make requests that exceed size limits expressed

Note also that the notion of `full` size goes away completely in the [3.0.0 Draft](https://iiif.io/api/image/3.0/#42-size).

**Comment by verglor** [comment]
The problem is, that I don't know what sizes I will need in advance. I want to be able to generate any image size on fly, but I also want to prevent anybody else to be able to generate many different sizes. The issue is very well described in [thumbor documentation](https://thumbor.readthedocs.io/en/latest/security.html#url-tampering). Parameters maxWidth, maxHeight and maxArea cover only very limited case. Signing is easy, effective and universal solution that prevents any unauthorized image processing.

I was thinking about creating shim for [thumbor](http://thumbor.org), but I found this missing feature is a dealbreaker.

**Comment by jpstroop** [comment]
Let me see if I understand correctly: You, as an authorized user with a valid `SECURITY_KEY` can request images of any size (`300x300`, `301x301`, etc.), but others can't? If I'm correct in my understanding, then let me make two points:

 1. You could, especially as a shim, still do a IIIF Level 0 implementation, because there is an assumption in our (IIIF space) that sophisticated clients, e.g. [OpenSeadragon](https://github.com/openseadragon/openseadragon/blob/master/src/iiiftilesource.js), [Leaflet](https://github.com/mejackreed/Leaflet-IIIF/blob/master/leaflet-iiif.js), will check the `info.json` service first, and behave accordingly. So you could list the tiles and sizes that the Thumbor service behind your IIIF shim is authorized to support.
 2. [We have different way of going about authorization](https://iiif.io/api/auth/1.0/). It's a little more complex because it goes beyond all-or-nothing access, based on the idea that, often, some access is better than no access--e.g. some users may only have access to a grayscale version, or a smaller size, or a more compressed derivative. We also try to solve for a bunch of CORS issues, since IIIF clients are often pulling content from multiple domains. It's a much bigger job, but off the top of my head I can't see why a thumbor shim couldn't use this pattern.

By the way--I was unaware of thumbor. Thanks for getting in touch!

**Comment by azaroth42** [comment]
I agree that this is covered by Authentication, without changes to the Image API. And yes, thanks for getting in touch :)

**Comment by azaroth42** [comment]
Discussion on call of 2019-02-27, other avenues for solving this issue that wouldn't involve changing the API directly. General agreement that this is out of scope for our work.  Again, thanks for raising the issue!
