### ISSUE TITLE
Guidance for deciding which of multiple logos to use

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1777]
If there are multiple logos available, how should the client decide which to display?

See https://github.com/IIIF/api/issues/1760 for discussion of allowing multiple `logo` property values in the Image and Presentation APIs in order to support with logos with text in different languages or other variants. See also https://github.com/IIIF/trc/issues/3 for discussion of the need for guidance about how the client should select which logo to display.

**Comment by sdellis** [comment]
The client can't decide which to display without adding additional properties, particularly properties like `lightness`, `color`, and `aspect-ratio`. 

If my client is using a "dark theme", then it should display a logo that has a "light" value. `Value` or `tone` are the terms used in the Elements of Design. The [lightness](https://en.wikipedia.org/wiki/Lightness) of the image also has implications for Accessibility and the ability to provide proper contrast between the logo and the background it rests on. Sometimes it's preferable to show a white or black logo, rather than one with color. Most institutions have [guidelines around logo use](https://communications.princeton.edu/guides-tools/logo-brand-assets#signature) that should be consulted.

Similarly, shape can be used to decide on an appropriate logo version. For designs in which a square/circular shape is preferred, the client might select an aspect ratio of `1:1` over one that is `1:2`.

Finally, a text version should be provided for screen readers so that all users are aware of the content and purpose of the image.

Hope this helps.

**Comment by azaroth42** [comment]
aspect ratio is already possible via `height` and `width`. Language is possible via `language.
The light/dark is a common case but does not have a solution in the current set of properties.  If there is an external solution we can point to, we should do so, in my opinion. If we have to invent something, then it can be prototyped in an extension and merged for 3.1.

For text, the logo can have a `label` and a `summary`, but as per #1288 we do not have a solution specifically for alt text.

**Comment by tomcrane** [comment]
2019-04-15 Eds agree that spec for `logo` should instruct the client to pick one, and that mechanisms for choosing belong in cookbook recipes which may involve extensions (e.g., as light/dark theme).

**Comment by zimeon** [comment]
Merged #1806
