### ISSUE TITLE
Clarify max does not ask for upscaling

### ISSUE THREAD

**Issue by mikeapp** [IIIF/api#1823]
@tomcrane  on `max` in discussion of #1814 :

> If the service supports sizeUpscaling, I can request both /max/ and /^max/ and get different sized images back. "maximum size available" is ambiguous - it is clarified by the next sentence, but perhaps this could be reinforced as "The extracted region is returned at the maximum size available, but will not be upscaled".

Also, for `^max`, the size is unspecified if none of the server restrictions are present.  Suggest it should be the same as `max` in this case.

**Comment by tomcrane** [comment]
> for `^max`, the size is unspecified if none of the server restrictions are present.

I think so, because:

>`sizeUpscaling` | Image sizes prefixed with ^ may be requested.

and

> A server that supports `sizeUpscaling` must specify `maxWidth` or `maxArea`

and from #1814 

> Requests for sizes prefixed with `^` _**that result in upscaling**_ _SHOULD_ result in a 501 (Not Implemented) status code if the server does not support upscaling

(my italics)

So I _think_ not a 501, because `^max` would not result in upscaling. 

>`sizeUpscaling` | Image sizes prefixed with ^ may be requested.

The absence of this feature does not mean that sizes with ^ _MAY NOT_ be requested (the discussion on the original upscaling issue).

So while asking for `^max` blindly is a bit odd (but asking for `^!1000,1000` blindly is not odd), it's not an error, and should be the same as `max` if it's not an upscaling service.

**Comment by zimeon** [comment]
Closing as #1826 merged to `image-prezi-rc2`
