### ISSUE TITLE
Update Image API 3.0 Changelog

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1830]
(Repurposing for RC4)

**Comment by zimeon** [comment]
Keeping this issue but moving forward to RC3 (hopefully final)

**Comment by zimeon** [comment]
We think these are now up to date but need a review. @mikeapp and @tomcrane will review

**Comment by tomcrane** [comment]
I've given this another read through.

One small thing - the upscaling syntax is mentioned, but only as a breaking change in discussion of tightening upscaling behaviour:

https://preview.iiif.io/api/image_prezi_rc3/api/image/3.0/change-log/#1-breaking-changes

It isn't introduced as a new feature in its own right - but does it need to be?

**Comment by mikeapp** [comment]
I've looked over issues since Beta2/image_prezi_rc2.   

Also noted:
The CC URLs issue #1874 (labelled both `image` and `presentation`) resulted in the note in Prezi's Rights section about rewriting links to HTTPS.   There's no corresponding note in the Image API Rights section, despite the same use case being described in both ("... and for example could be used to display an icon representing the rights assertions.").   Rob also mentioned Image https://github.com/IIIF/api/issues/1874#issuecomment-542369663 but it dropped from the discussion after.   As a result #1874 is linked from the Presentation change log but not the Image one.

**Comment by azaroth42** [comment]
Closing, done :)
