### ISSUE TITLE
preferredFormats should have use case, example

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#1838]
The description of the preferredFormats property in the Image API 3.0 beta draft does not have an example in its section (5.5) and should for consistency and clarity.

Also noted on the TRC review of the issue is that the description lacks sufficient informative discussion to know when publishers might want to use the function, and what clients might be expected to do with it when encountered. Some further use case description would help understanding as to its purpose and intended effects.

**Comment by mixterj** [comment]
The issue for me is what does 'preferred' mean and how should it be interpreted/used by data consumers. Clarifying examples of the logic for using the property would be helpful. Such as:

- bandwidth efficiency for mobile image viewing
- Highest quality for high-fidelity image viewing 

If these are not listed as examples to follow (or ideally explicitly called out) then a consumer of the info.json will have no idea what the point/reasoning behind the ordering is. This will result in at best the consumer just taking the first format in the list or worse just ignoring the property all together. I guess one could infer the type or preferred ordering by the formats in the list but that logic breaks down given the first example in issue 21

> line drawings compressed to 20k as png vs 220k as jpg

which, if I understood correctly, was to select the smaller png because it was 'more accurate' than the larger jpg.

**Comment by tomcrane** [comment]
> a consumer of the info.json will have no idea what the point/reasoning behind the ordering is. This will result in at best the consumer just taking the first format in the list ...

Isn't that what we want though? The existence of the property is so that a client doesn't have to reason about which format to choose (previously, it would) or any meaning behind the order. It doesn't have to make impossible qualitative decisions, it just blindly follows the info.json, choosing the first format that it knows it can deal with, then falling back through the others. And if it wants to offer users a choice of other formats, it can still do that.

**Comment by mixterj** [comment]
The problem is understanding of what the preferred order is in the preferredFormat list. Is it for bandwidth optimization - in which case it might not be idea for desktop usage, is it for the highest fidelity - in which case it would not be good for mobile use, is it for most accurate representation of the original - not sure of issues here ;). The point is the property is so ambiguous about what preferred means, it almost makes the property useless.

A potential workaround would be to make the property a single string. Then the client has the binary choose to either use it or not. Then the 'order' of preferredFormat is, 'the data produced says it prefers this one', and the reasoning/methodology behind the 'order' is, 'there is only one and it is because [the data producer] says so'.

Another workaround is to figure out the use cases for why we want 'preferredFormat' and then make a property for each use case - i.e. preferredQuality, preferredBandwidth, etc. I know that seems silly but otherwise what we are doing is basically cramming all of those semantics into 'preferredFormat' and worse then dropping the original semantics.

**Comment by eroux** [comment]
well, here's a use case: I have bitonal images. png compression is 20k, jpg compression is 220k. visually they are more or less equivalents. I want the client to use png in all cases so that I can save bandwidth.

Another use case: we want users to use webp in some cases (like grayscale) when their browser allows it, also to save bandwidth.

Are these sensible use cases? If not, why aren't they?

**Comment by mixterj** [comment]
Yeah those use cases all make sense. I was not suggesting that there were not valid use cases but just that the use cases in the original proposal seemed to suggest different/multiple definitions of what 'preferred' means. The issue is that if 'preferred' changes provider by provider and it is not clear what the server's definition of 'preferred' is then there could be potential problems. Also, if there is a 'preferred' then I would argue there should be a single string value there (not a list of one or more). The main problem is when you have a preferredFormats (with no definition of what 'preferred' represents) and there is a list of values that deliver back varying type/size/fidelity of resources. Then it will be very confusing to a client to determine what to use or why they are using a given one.

Your use cases make a lot of sense because your two compressions are visually more or less the same, and if you are just viewing the images in something like OpenSeadragon, it really makes no difference, so you might as well define the png as the preferred. But that is not the use case in all instances

So I think a perfect use case is 'bandwidth efficiency'. I just want to make sure that there are not other major use case that might contradict the 'preferredFormats' order in a 'bandwidth efficiency' use case - like preferring to deliver the highest-fidelity resource or something similar.

**Comment by eroux** [comment]
Ok I understand better, thanks!

Maybe

```json
"PreferredFormats": {
   "bandwidth": ["png"]
}
```

could make sense yes, why not...

I still think a table is necessary: we're currently exploring using webp; in case it works, we would want webp, else png. In that case a single string cannot work
