### ISSUE TITLE
Consider adding `max` parameter for Autocomplete request -

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#2146]
We have a `min` parameter (https://iiif.io/api/search/1.0/#request), there might be utility in a `max` parameter to omit very common terms in the index

(From editors' meeting 2022-06-10)

**Comment by azaroth42** [comment]
Should this be included in Search 3.0? (thumbs up/down on the comment please)

**Comment by zimeon** [comment]
I would like to look at examples of other search services that leverage a feature like this to better understand the use case

**Comment by azaroth42** [comment]
Assuming that the terms are ordered by frequency, rather than strictly alphanumeric sort, and stopwords are not excluded, then the top words will likely be useless for autocomplete - 'th' --> the, then, there, these, this, ... and so on.

`max` could exclude those ... but to be less optimistic, it would be (a) better to have the server exclude these automatically, and (b) the max number would be server/index dependent and hard for the client to predict.

**Comment by zimeon** [comment]
I think if we wanted to exclude common words for autocomplete as you describe then `max` would not want to be a number but instead a frequency so that it scales with size of the resource (i.e. nothing that occurs more than 5% of the time). But even then, I think know what this threshold should be would be very difficult in the general case. I agree that this is probably left up to the server though (which might be configured with knowledge of content) and this not put into the spec.

**Comment by azaroth42** [comment]
Changing my opinion from :eyes: to :-1: given the discussion
