### ISSUE TITLE
Make non-painting annos MUST for @id

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#456]
Cf. #439 which added _SHOULD_ in v2.1 (see http://iiif.io/api/presentation/2.1/#b-summary-of-metadata-requirements & http://iiif.io/api/presentation/2.1/#comment-annotations )

**Comment by azaroth42** [comment]
We should confirm this one, even though we can't act on it yet, so we don't end up discussing it again.
My vote: :+1:

**Comment by zimeon** [comment]
Agree, :+1:

**Comment by mikeapp** [comment]
Agree :+1:

**Comment by jpstroop** [comment]
yup :+1:

**Comment by jkeck** [comment]
This came up in some of our current Spotlight work.  @jpstroop suggested adding our use case for making painting annos a MUST for `@id` here.

We are creating an interface in Spotlight that will allow users to save a cropping of a IIIF backed image resource for use around their exhibit. We will be storing `@id`s from the given IIIF manifest down to the annotation level in order to support canvases with multiple painting annotations.  We will be storing the service `@id` as well for performance reasons. We want to store the annotation `@id` so that we can re-construct the service `@id` (and cropped image url) for the correct image resource in the case of a file renaming, sequence change, etc.  If we encounter multiple painting annotations in a canvas without IDs at present we will need to simply need to select the first.

Please let me know if you need any clarification on this, or if adding these details somewhere else would be more appropriate.

**Comment by azaroth42** [comment]
@jkeck Will you be providing access to the annotations themselves via their URIs as well?

**Comment by jkeck** [comment]
@azaroth42 not planning on it currently, although we may reconsider that if they were MUST and required to be dereferenced.

**Comment by azaroth42** [comment]
Then I don't see the interoperability requirement for having identifiers for the painting annotations? What is someone other than your own system going to do with them? There's no problem with having them, but why should _everyone_ be required to create and maintain them?

**Comment by azaroth42** [comment]
Actually ... we should be good and use a new issue...

**Comment by jpstroop** [comment]
Consensus on 2 August 2017 call that we should do this

**Comment by zimeon** [comment]
:+1: agreed in Toronto WG meeting that `@id` is required in order to follow the web annotation model

**Comment by azaroth42** [comment]
Done: http://prezi3.iiif.io/api/presentation/3.0/#id

**Comment by zimeon** [comment]
:+1: agree done
