### ISSUE TITLE
Sitemaps for Discovery

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#465]
Eds & @anarchivist to draft a recommendation for using [Google Image Sitemap Extensions](https://support.google.com/webmasters/answer/178636?hl=en) + additional IIIF extensions to **get all teh maniphests**. Something along these lines:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
 <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:iiif="http://iiif.io/sitemap/0.1">
 <url>
   <loc>http://example.com/sample.html</loc>
   <iiif:manifest>http://example.com/sample/manifest</iiif:manifest>
   <image:image>
     <image:loc>http://example.com/image/1/full/full/0/default.jpg</image:loc>
     <iiif:base-uri>http://example.com/image/1</iiif:base-uri>
   </image:image>
   <image:image>
     <image:loc>http://example.com/image/2/full/full/0/default.jpg</image:loc>
     <iiif:base-uri>http://example.com/image/2</iiif:base-uri>
   </image:image>
 </url> 
</urlset> 
```

**Comment by zimeon** [comment]
I'm a strongly support using sitemaps. However, I'm not sure about the image extensions approach unless we feel that the approach above is a successful and desirable way to get the major search engines to index the `http://example.com/sample.html` page, and the `http://example.com/image/1/full/full/0/default.jpg` and `http://example.com/image/2/full/full/0/default.jpg` images (and we want to mandate existence of the `http://example.com/sample.html`). Otherwise I would be more inclined to adopt an approach that puts the key resource URIs of interest into the \<loc> elements, and consider using some the the [ResourceSync extensions](http://www.openarchives.org/rs/1.0/resourcesync) to provide any additional description that might be useful.

**Comment by zimeon** [comment]
How to allow IIIF servers that want their stuff indexed by Google etc. to do so with a IIIF sitemap or sitemaps using some IIIF standard URI ( that isn't /sitemap.xml)? I think we could suggest two approaches:

> If you want commodity search engines to find your images/manifests/etc. then make sure you have either:
>
> a) {prefix}/image_sitemap.xml (or whatever it might be called) as a redirect to /sitemap.xml which is then in the normal and expected location to be picked up by commodity search services
>
> b) Include a /sitemap.xml on the same server that is a sitemap index (see <http://www.sitemaps.org/protocol.html#index> ) which lists one or more IIIF specific sitemaps with URI pattern {prefix}/image_sitemap.xml (or whatever it might be called) on that same server. (Note that this option is not available for the case of servers with more images (>50k) that may be specified in a single sitemap, option a) would have to be used instead)

**Comment by azaroth42** [comment]
Proposal to make this, and all other `discovery` topics notes rather than a hodge-podge specification document.

**Comment by zimeon** [comment]
Proposal above was for use of Google sitemap extensions. Consensus (or at least majority) opinion in Discovery session at The Hague today was to use plain sitemaps (IIIF resources in `<url>` elements) for harvesting. Might also specify method using Collections and/or use ResourceSync extensions.

IMO, this issue is stale, propose close `wontfix`

**Comment by azaroth42** [comment]
Closing wontfix in favor of other `discovery` discussion.
