### ISSUE TITLE
Deprecate pct: syntax

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#478]
What does it get us? You have to get the info.json to know the size to calculate the percentage anyway, and clients may use different decimal precision which is bad for caches. Could note that is is deprecated in 2.1 for exclusion in 3.0

**Comment by azaroth42** [comment]
Discuss in Princeton at Eds' meeting.

**Comment by azaroth42** [comment]
Eds agree. Deprecation warnings added to spec in 2.1; @jpstroop to send email to iiif-discuss to seek objections.

**Comment by jpstroop** [comment]
https://groups.google.com/d/msg/iiif-discuss/CkYj3vjse5Y/Qo6MQ9swr28J

**Comment by azaroth42** [comment]
For 10/7 call, I propose to remove deprecation warnings. The use cases in the discussion linked are convincing to me at least :)

**Comment by zimeon** [comment]
Editors agree: remove deprecation warning from 2.1, revisit for 3.0 based on additional experience

**Comment by jpstroop** [comment]
Note also that the size `pct` syntax is required for level 1, but the region `pct` syntax is only required for level 2. I'd support making it all level2 or greater.

**Comment by robcast** [comment]
I think we should split this issue as using `pct` for size or for region are very different issues.

Using `pct` for size does not seem to make much sense to me as I have to know the size of the image on the server to know what size I'll get. If I know the size already I can just do the multiplication myself and use an absolute size.

Using `pct` for a region is an important feature because it is the only way to specify an image region without knowing the absolute image size. 

I think having a relative measure like `pct` is important for image annotations or other uses where a region gets saved separate from the original image because with the relative measure the region can be reconstructed even if the image resolution changes. (Another way would be to save the size of the original image with the reference... I'll need to talk to the annotation people about that idea.)

**Comment by jpstroop** [comment]
@IIIF/editors propose: move all `pct` requirements to level 2.

**Comment by jpstroop** [comment]
Closed with f89824768c917d4956f8460a21cf1d764cac4f00

**Comment by zimeon** [comment]
Noting use of `pct:` in Wikidata: https://www.wikidata.org/wiki/Property:P2677
