### ISSUE TITLE
Document drag and drop pattern

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#602]
At the IIF Shimathon 2015-09-29/30 at UPenn in Philly we came up with a pattern for drag and drop functionality that was demonstrated in Mirador. 
- Description: http://zimeon.github.io/iiif-dragndrop/
- Discussion thread with demo: https://groups.google.com/forum/#!searchin/iiif-discuss/drag/iiif-discuss/lrR8OJMl_qk/U6uAyFcSCwAJ

This should probably be written as an implementation note like the [JSON-LD Frames Implementation Notes](http://iiif.io/api/annex/notes/frames.html) and [Rotation](http://iiif.io/api/annex/notes/rotation.html).

**Comment by zimeon** [comment]
@mattmcgrattan suggested on IIIF-Discuss that Digital.Bodleian might be early to implement. The current IIIF logo link to manifest could easily be extended to do this. Eg. the current code on [Menologion folio 1v](http://digital.bodleian.ox.ac.uk/inquire/Discover/Search/#/?p=c+1,t+,rsrs+0,rsps+10,fa+ox%3Acollection%5EWestern%20Manuscripts,so+ox%3Asort%5Easc,scids+,pid+a77c8264-9651-49c8-bf6b-f6d9f9077586,vi+0a03d21d-0807-405b-b0d1-dad366106e28) has the image as:

```
<a data-bind="attr:{href: 'http://iiif.bodleian.ox.ac.uk/iiif/manifest/'+resultCurrent().id+'.json'}" target="_blank" title="IIIF Manifest">
<img src="../../Content/images/logo-iiif-34x30.png" alt="IIIF Manifest">
</a>
```

by adding manifest (and canvas for specific folio) params to the href.

**Comment by mattmcgrattan** [comment]
For info: This will happen as soon as I can find a few hours to rewrite some of the backend code to provide the information, it's not currently provided to the UI, and change the manifest creation web service to accept requests with the Drag and Drop syntax, so that someone can drag into a view, or click to see the manifest itself.

Ideally before Ghent.

Matt


Dr Matthew McGrattan
Collections Delivery Architect & Acting Head of Digital Research
Bodleian Digital Library Systems and Services
tel: 01865 280035
matthew.mcgrattan@bodleian.ox.ac.uk
________________________________

**Comment by azaroth42** [comment]
Why is this deferred? Propose removing label:defer :)

**Comment by zimeon** [comment]
Agree, label:defer removed. With input from others on IIIF-Discuss (<https://groups.google.com/forum/#!topic/iiif-discuss/US2tKBn2Wno>) it seems there is support to move ahead. I agree that a key element is that the note should include a nice CC0 icon to use. How do we make that happen? As we can see from my [demo icon](http://zimeon.github.io/iiif-dragndrop/iiif-dragndrop-100px.png), such work is not in _my_ skillset

**Comment by mattmcgrattan** [comment]
So, I now have drag and drop up and working on the dev branch of Digital.Bodleian using the IIIF icon I was using before, as per https://github.com/IIIF/iiif.io/issues/602#issuecomment-155851252. 

I just need to tweak the manifest handler app that we run, so that if someone clicks on the link, rather than drags, they get directed to the right manifest.

I expect it'll be live early next week.

**Comment by mattmcgrattan** [comment]
So, Drag and Drop is up now on the dev branch of Digital.Bod:

http://digital.bodleian.ox.ac.uk/inquire-dev/Discover/Search/#/?p=c+1,t+,rsrs+0,rsps+10,fa+,so+ox%3Asort%5Easc,scids+,pid+,vi+

I'd appreciate it if someone could give it a prod. I've tested the drag and drop icon against Mirador, and against the UV, and both seem fine. 

Click rather than drag redirects to the manifest.

**Comment by zimeon** [comment]
@mattmcgrattan - Looks like it is working fine to me. Drag works to Mirador, OSD and my little [debug JS ](http://zimeon.github.io/iiif-dragndrop/droptest.html).

**Comment by mattmcgrattan** [comment]
Now deployed on the production Digital.Bod.

**Comment by mattmcgrattan** [comment]
We should have a collection drag and drop pattern, too. With the UV and soon Mirador supporting collections, it would be good to be able to drag a collection in, not just manifest/image.

**Comment by mikeapp** [comment]
:+1:

**Comment by zimeon** [comment]
Should add this as <http://iiif.io/api/annex/notes/drag-and-drop>

Current use includes:
  * Supported by UV and Mirador
  * DigitalBodleian (e.g. <http://digital.bodleian.ox.ac.uk/inquire/Discover/Search/#/?p=c+1,t+,rsrs+0,rsps+10,fa+ox%3Acollection%5EWestern%20Manuscripts,so+ox%3Asort%5Easc,scids+,pid+eeb272cc-bb48-44b0-9ee3-2cee0338a691,vi+>)
  * eCodices (e.g. <http://www.e-codices.unifr.ch/en/searchresult/list/one/kba/0016-3>)
  * NGA had demo but doesn't appear to be on production

At present is seems that everyone uses the normal IIIF logo. Might still be good to have a specialized version for drag-and-drop but not a blocker.

**Comment by zimeon** [comment]
Have started work on this in branch https://github.com/IIIF/iiif.io/tree/drag-and-drop , not complete yet

**Comment by zimeon** [comment]
Consensus is that drag and drop should be replaced by a more general "import to viewers" strategy, and work on this is happening in the discovery TSG. See https://github.com/IIIF/discovery/issues/18
