### ISSUE TITLE
Allow `top` for Collections

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#859]
Not sure if we discussed this or not, but it seems like allowing (but not requiring) the top `viewingHint` on the topmost Collection for an institution, as well as the topmost range of a Manifest wouldn't hurt.

We could do this in 2.2, or in 3.0, as it's an addition not a backwards incompatible change.

**Comment by azaroth42** [comment]
Discussion on 08/30:  Premature for the discovery use case (this is the top of the hierarchy of institutional collections).  Potentially useful for __rendering__ use cases of knowing when you've reached the top of an intellectual hierarchy such as an archive, but might not be as useful as originally expected.

Requesting further use cases and requirements for this in order to un-`defer`.

**Comment by zimeon** [comment]
I don't think `top` has very clear or useful meaning. For the discovery use case there will need to be an external list of top-level collections, so `top` doesn't serve that purpose. Inside a collection hierarchy one would expect to follow `within` links until there is no `within` to have found a top (thus absence of `within` implies `top`). If `top` is intended to have some other intellectual meaning, so that one might use `top` in a collection that doesn't have `within`, then this seems different to the discovery case and has very uncertain meaning. I propose close-wontfix.

**Comment by azaroth42** [comment]
:+1: to close wontfix.

**Comment by tomcrane** [comment]
:+1:

**Comment by mikeapp** [comment]
👍 to close wontfix
