### ISSUE TITLE
Disallow @graph pattern

### ISSUE THREAD

**Issue by azaroth42** [IIIF/api#920]
In the implementation notes for the Presentation API, we say that clients should process the `@graph` JSON-LD keyword if they want to be fully conforming.  Either this should be a requirement in the text of the specification, or it should just be disallowed.

My preference is to disallow its use completely and require servers to output the correct form.  `@graph` is required when the graph to be serialized is unconnected, however that will never occur in IIIF as we define the structure very carefully.  Any custom fields can be added via extensions, which we allow for.

The use case put forwards for `@graph` is the separation of metadata about the representation and the object, however that's unnecessary in IIIF -- we have metadata about the resource being depicted/described in `metadata`, so any use of (for example) dcterms:modified could be unambiguously interpreted as the modification timestamp for the manifest.

The cost of allowing `@graph` is not as high as some other choices, if its value is the full manifest structure.  However if you can generate the right structure, you can (as above) simply serve it from the URI directly.  If the server can't generate the right structure, I don't think we should consider it as an implementation of IIIF, and thus expect the client to use frames (and likely some hand crafting to get things in the right shape after that) to interpret the data.  I don't think we would expect the client to interpret a list of every node (including all the rdf:List blank nodes separately), but that is implicitly legal according to the implementation note.

**Comment by christopher-johnson** [comment]
Perhaps this issue should be addressed directly in relation to the JSON-LD specification where @graph is an integral part.  If a server is delivering content-type "application/ld+json", then theoretically, the response is governed by the scope of that specification.  If a client requests "application/ld+json", then it should be prepared to handle the content-type.   So, essentially the client always needs to conform to the content-type it requests.  It would be possible to use content negotiation to discriminate between @graph response and the "correct" response simply by having the client request "application/json"  instead which seems to be the more prevalent serialization for manifests currently.

**Comment by zimeon** [comment]
It seems to me that we are already profiling JSON-LD by the mandate of a specific `@context`, the goal being to support non-LD-aware clients. So far, none of the major clients for IIIF are LD-aware, and I think we should be very careful of making any choice that would lead us down the road of demanding it.

If we were to say that clients should support conneg between plain JSON and JSON-LD then I suspect we'd end up making JSON support a _MUST_ and JSON-LD support a _SHOULD_ for fear of raising the barrier to implementation. I think that would likely decrease use of JSON-LD within the community which isn't what we want. It seems to be a tricky balancing act.

**Comment by christopher-johnson** [comment]
The client simply needs to make a decision on what content-type it can accept.  And, unfortunately, by disallowing `@graph,` the IIIF is fundamentally indicating that clients _MUST NOT_ support "application/ld+json" content-type.  I do not think that is rational if it aims to be LD-aware.  Rather, I would advise to include a statement in the specification to the effect that if a client wants to support JSON-LD, then it _MUST_ add an Accept "application/ld+json" header in its request.  This then facilitates the client-side decision logic that can route the LD-server response to the appropriate deserialization routine.  For non-LD capable clients, a default deserialization handler would then always expect that the server response would be "application/json" and not break because it had a legal JSON-LD keyword.

**Comment by azaroth42** [comment]
@christopher-johnson I'm curious as to why you think that disallowing `@graph` means that it's not JSON-LD?

**Comment by christopher-johnson** [comment]
The core of the issue here does not have to do with what the client can do, but rather with what it should expect.  A server that is producing content-type JSON-LD can use any JSON-LD legal keywords (and if it is a triplestore will use always @graph) in its response, and the client MUST be able to parse them if it accepts that content-type.  What is and what is not JSON-LD is bound completely to the W3C specification and not to a particular implementation.

I am not suggesting that a response without @graph is not JSON-LD, but in most cases this will not be born as RDF and rather be a normal JSON source "pretending" to be linked data.  As mentioned previously, this duality is a huge benefit of the format, because it allows a client to transform out linked data from a non-linked data source, if that is a requirement.

**Comment by azaroth42** [comment]
I agree that the issue is about what the client should expect.  IIIF has consciously and deliberately made the decision that clients should not expect `@graph` (and the implementation note is a special case which this issue would then remove).  I don't see anywhere in the specification for JSON-LD that clients MUST be able to parse them if they accept that content type however. Do you have a reference for that? 

In particular, I note that section [6.13 on Named Graphs](https://www.w3.org/TR/json-ld/#named-graphs) is not even normative, which is where `@graph` is described.  So I'm afraid that I (and the spec) disagree with your argument here.

**Comment by christopher-johnson** [comment]
@lanthaler points out in [this discussion](https://github.com/json-ld/json-ld.org/issues/182#issuecomment-10125820) that "Every processor MUST expect named graphs when parsing a JSON-LD document".  
I cannot answer why 6.13 is not normative, but this fact alone does not invalidate that section.  

There do exist methods for a client to profile how it expects a JSON-LD response.  Check this [issue](http://stackoverflow.com/questions/39551829/usage-for-profile-parameter-for-json-ld-requests).  I know that Fedora 4+ has implemented JSON-LD profiling.  

As suggested in the "graph" versus "dataset" discussion referenced above, one possible solution would be to register a profile that enforces the IIIF APIs expectations of a default graph "dataset" response.  However, I really feel that this is going in a impractical direction.

My feeling from the point of view of the client developer also supports `@graph` as a JSON-LD root node as you can always parse the response into a single object.  It really does simplify things.  Additionally, the [Hydra Core vocabulary](https://www.hydra-cg.com/spec/latest/core/#documenting-a-web-api) could also facilitate the API client expectations that you are advocating, and reduce the amount of hardcoding that exists in the current IIIF client implementations.

**Comment by zimeon** [comment]
To me, they key issue is that we want a single serialization that works for both JSON-LD clients and plain-JSON clients. In order to facilitate the latter, it is better to specify a more restrictive profile without the use of `@graph`.

Requiring servers to support both JSON-LD and JSON with different forms via conneg seems an unnecessary complication that would make static file implementations tough. I'm also not sure what would be gained -- if the form that works for plain-JSON clients is a complete and valid JSON-LD serialization, then any JSON-LD client is happy.

At present, all the major IIIF clients (or is it all clients?) are plain-JSON clients without JSON-LD facilities. I think it is great that we adopt the rigor of making IIIF data work as RDF and I look forward to more work using the responses as JSON-LD (hence my [SWIB16 workshop](http://swib.org/swib16/programme.html#abs03)), but we should be aware that it is plain-JSON compatibility that is facilitating rapid adoption. I also note a separate issue about [changing the framing algorithm to avoid `@graph` when not needed](https://github.com/json-ld/json-ld.org/issues/435).

**Comment by christopher-johnson** [comment]
Changing the framing ( and compaction and flattening?) algorithms will definitely help me.  Thank you for taking this initiative. I had previously considered modifying the jsonld library to do this , but I have opted instead to make local changes for my linked data sourced [UV prototype](http://uv.b-ol.de) and [Mirador prototype] (http://mirador.b-ol.de/).  I do not like having to build and maintain forks, though, and this is not a sustainable solution considering the rapid pace of the client development.

I do think that the question of a "hypermedia-driven" API is still on the table and relevant to this issue.  I know that the current IIIF client implementations are brittle with a lot of hard-coding and I think that it is very optimistic to expect total conformity to a restrictive profile with all of the potential that exists in the IIIF universe.  And you certainly know better than I the problems associated with API versioning... I do see the need to "keep it simple" though as completely valid.

I look forward to meeting you in Bonn in a few weeks.

**Comment by christopher-johnson** [comment]
As a footnote to this, I have resolved the `@graph` issue in my manifest service and the change is so trivial that I feel silly now for having made such a fuss about the nebulous specification.    

FYI: My problem originated in the jsonld library [here](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L577).  There is a boolean that if it is set to "false" instead of "true", then the compaction does not return `@graph`.  I am already using a forked version of the library, so it is a very simple fix.  I am happy because now I can indeed produce interoperable manifests!

There may still be an open question about [JsonLdApi.java](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java), however, that would affect Jena.  And, what I suspect is that the [fromRDF](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java#L1992) method always returns `@graph`, unlike the javascript library that does not (fortunately).  My original plan was to CONSTRUCT the manifest graph directly from the triplestore as JSON-LD, but in most (if not all) current triplestore implementations, a CONSTRUCT query JSON-LD response will always return `@graph`.   Instead, I just get n3 and then use the js library to transform and frame it, which works fine.

**Comment by azaroth42** [comment]
https://github.com/json-ld/json-ld.org/issues/435 is the upstream issue for JSON-LD 1.1

**Comment by azaroth42** [comment]
Discussion on 8/2/17:  Agreement to disallow @graph completely.

**Comment by christopher-johnson** [comment]
FYI: It is currently still not possible to use the Java JsonLdApi to compact a JsonLd document without `@graph`.  The core problem is that the JsonLdProcessor result type for a JsonLd compacted or framed document is understood to be a Map<String,Object> where String is a key like `@context`.  In the IIIF expected document, you have Map <`@context`, Object> followed by an "anonymous" Object  {..}.  

I sincerely believe that not providing for a String key like `@graph` for the manifest object is a major problem for the Java JsonLd Api.  I am surprised that this was not recognized as being of some consequence in your discussion.

**Comment by workergnome** [comment]
Was not in the call, but I agree that unless the ability to implement this is added to Framing, this is a problem because it adds a lot of complexity to generating manifests from LOD—it requires a system that does custom post-processing.

**Comment by azaroth42** [comment]
The assumption is that this will be enabled by the JSON-LD 1.1 algorithms, which we're requiring for Language Maps and so forth regardless.  The post-processing for removing the `@graph` wrapper will be the least of anyone's worries without those updates to the codebases :)

**Comment by zimeon** [comment]
:+1: agreed at Toronto WG meeting

**Comment by azaroth42** [comment]
Editorial:  
Propose to add the requirement to this section: http://prezi3.iiif.io/api/presentation/3.0/#linked-data-context-and-extensions

**Comment by azaroth42** [comment]
Closed by #1306
